// Build script - generates levels.js with 200 levels
const fs = require('fs');
const path = require('path');

const GAME_WORLDS = [
  { id: "animal-island", title: "动物岛", englishTitle: "Animal Island", scene: ["🐱", "🏝️", "🐾"], description: "学习动物名称、颜色和简单动作" },
  { id: "school-island", title: "校园岛", englishTitle: "School Island", scene: ["🏫", "📚", "✏️"], description: "学习校园用语和课堂表达" },
  { id: "life-island", title: "生活岛", englishTitle: "Life Island", scene: ["🏡", "🥛", "👟"], description: "学习日常生活英语表达" },
  { id: "food-island", title: "美食岛", englishTitle: "Food Island", scene: ["🍕", "🍎", "🍰"], description: "学习食物和饮品名称" },
  { id: "feeling-island", title: "情感岛", englishTitle: "Feeling Island", scene: ["😄", "💖", "🌟"], description: "学习表达感受和情绪" },
  { id: "nature-island", title: "自然岛", englishTitle: "Nature Island", scene: ["🌈", "🌸", "☀️"], description: "学习自然和天气词汇" },
  { id: "family-island", title: "家庭岛", englishTitle: "Family Island", scene: ["👨‍👩‍👧", "🏠", "❤️"], description: "学习家庭成员和家居词汇" },
  { id: "sport-island", title: "运动岛", englishTitle: "Sport Island", scene: ["⚽", "🏊", "🏃"], description: "学习动作和运动词汇" },
  { id: "body-island", title: "身体岛", englishTitle: "Body Island", scene: ["🧍", "👁️", "✋"], description: "学习身体部位和感官词汇" },
  { id: "rainbow-island", title: "彩虹岛", englishTitle: "Rainbow Island", scene: ["🌈", "🎓", "✨"], description: "综合复习所有英语和成语" },
];

// Helper functions
function choice(n, wId, title, skill, inst, prompt, words, opts, answer, success, completion, reward) {
  return { id: `level-${n}`, number: n, worldId: wId, title, skill, type: "choice", instruction: inst, prompt, words, options: opts, answer, success, completion, sceneReward: reward };
}
function story(n, wId, title, skill, inst, prompt, words, opts, answer, success, completion, reward) {
  return { id: `level-${n}`, number: n, worldId: wId, title, skill, type: "story", instruction: inst, prompt, words, options: opts, answer, success, completion, sceneReward: reward };
}
function wordForge(n, wId, title, skill, inst, prompt, words, letters, answer, success, completion, reward) {
  return { id: `level-${n}`, number: n, worldId: wId, title, skill, type: "word-forge", instruction: inst, prompt, words, letters, answer, success, completion, sceneReward: reward };
}
function echo(n, wId, title, skill, inst, prompt, words, accepted, success, completion, reward) {
  return { id: `level-${n}`, number: n, worldId: wId, title, skill, type: "echo", instruction: inst, prompt, words, accepted, success, completion, sceneReward: reward };
}
function boss(n, wId, title, skill, inst, prompt, words, steps, success, completion, completionTitle, reward) {
  return { id: `level-${n}`, number: n, worldId: wId, title, skill, type: "boss", instruction: inst, prompt, words, steps, success, completion, completionTitle, sceneReward: reward };
}

const L = [];

// ===== 动物岛 英语 (1-10) =====
L.push(choice(1,"animal-island","找到小猫","听音选动物","听到口令后，选择正确的动物","Find the cat.",["cat"],[{id:"dog",emoji:"🐶",label:"dog"},{id:"cat",emoji:"🐱",label:"cat"},{id:"bird",emoji:"🐦",label:"bird"}],"cat","Yes! Cat! 🐱","你听懂了 cat 🐱","🐱 小猫回到了动物岛"));
L.push(choice(2,"animal-island","找到小狗","听音选动物","听到口令后，选择正确的动物","Find the dog.",["dog"],[{id:"cat",emoji:"🐱",label:"cat"},{id:"dog",emoji:"🐶",label:"dog"},{id:"fish",emoji:"🐟",label:"fish"}],"dog","Yes! Dog! 🐶","你听懂了 dog 🐶","🐶 小狗回到了动物岛"));
L.push(choice(3,"animal-island","红色的球","听颜色指令","听到口令后，选择正确颜色的球","Find the red ball.",["red","ball"],[{id:"blue",emoji:"🔵",label:"blue"},{id:"red",emoji:"🔴",label:"red"},{id:"green",emoji:"🟢",label:"green"}],"red","Yes! Red ball! 🔴","你听懂了 red ball","🔴 红球找到了"));
L.push(choice(4,"animal-island","大还是小","听音选大小","听到口令后，选择正确的","Find the big elephant.",["big","elephant"],[{id:"small",emoji:"🐭",label:"small"},{id:"big",emoji:"🐘",label:"big"},{id:"tiny",emoji:"🐜",label:"tiny"}],"big","Yes! Big elephant! 🐘","你听懂了 big","🐘 大象出现"));
L.push(story(5,"animal-island","谁在树上","听句子选场景","听句子，选择它描述的画面","I see a bird.",["bird","I see a"],[{id:"fish",emoji:"🐟🌊",label:"a fish in water"},{id:"bird",emoji:"🐦🌳",label:"a bird in a tree"},{id:"cat",emoji:"🐱📦",label:"a cat in a box"}],"bird","Yes! I see a bird! 🐦","你听懂了 I see a bird","🌳 鸟窝出现"));
L.push(story(6,"animal-island","小兔子在跑","听句子选场景","听句子，选择它描述的画面","The rabbit is running.",["rabbit","running"],[{id:"sleep",emoji:"🐰💤",label:"rabbit sleeping"},{id:"run",emoji:"🐰🏃",label:"rabbit running"},{id:"eat",emoji:"🐰🥕",label:"rabbit eating"}],"run","Yes! The rabbit is running! 🐰","你听懂了 The rabbit is running","🐰 小兔子跑来了"));
L.push(wordForge(7,"animal-island","拼出 DOG","按顺序拼单词","按听到的顺序点字母","Build dog. D. O. G. Dog.",["dog","d","o","g"],["O","D","G"],"DOG","Yes! D. O. G. Dog!","你拼出了 DOG","🐶 小狗出来了"));
L.push(echo(8,"animal-island","跟读：我看到一条鱼","听示范并跟读","听完示范，再说同一句话","I see a fish.",["fish","I see a"],["i see a fish","see a fish","fish"],"Yes! I see a fish! 🐟","你说出了 I see a fish","🐟 小鱼游来了"));
L.push(choice(9,"animal-island","找到蓝色的小鸟","听音选颜色动物","听到口令后，选择正确的","Find the blue bird.",["blue","bird"],[{id:"red-bird",emoji:"🐦🔴",label:"red bird"},{id:"blue-bird",emoji:"🐦🔵",label:"blue bird"},{id:"green-frog",emoji:"🐸🟢",label:"green frog"}],"blue-bird","Yes! Blue bird! 🐦","你听懂了 blue bird","🐦 蓝鸟飞来"));
L.push(boss(10,"animal-island","动物岛 Boss","四项综合任务","完成四项任务，点亮动物岛","Let's save Animal Island!",["cat","dog","red","big"],[{type:"choice",instruction:"选择小猫",prompt:"Find the cat.",answer:"cat",options:[{id:"dog",emoji:"🐶",label:"dog"},{id:"cat",emoji:"🐱",label:"cat"},{id:"bird",emoji:"🐦",label:"bird"}]},{type:"word-forge",instruction:"拼出 DOG",prompt:"Build dog. D. O. G.",answer:"DOG",letters:["G","D","O"]},{type:"choice",instruction:"选择红色",prompt:"Find red.",answer:"red",options:[{id:"blue",emoji:"🔵",label:"blue"},{id:"red",emoji:"🔴",label:"red"},{id:"green",emoji:"🟢",label:"green"}]},{type:"echo",instruction:"跟读句子",prompt:"I see a big cat.",accepted:["i see a big cat","see a big cat","big cat"]}],"Animal Island is saved!","你完成了动物岛的所有挑战","动物岛得救了！","✨ 动物岛完全修复"));

// ===== 动物岛 成语 (11-20) =====
L.push(story(11,"animal-island","一心一意","看画面理解成语","哪个孩子在专心做同一件事","一心一意。Focus!",["一心一意","focus"],[{id:"distracted",emoji:"📺🎮📖😵",label:"同时做很多事"},{id:"focus",emoji:"🧒📖✨",label:"专心读一本书"},{id:"sleep",emoji:"🛌💤",label:"正在睡觉"}],"focus","一心一意，就是专心做好一件事。Focus!","你理解了 一心一意 (focus) 🎯","🎯 专注星点亮了"));
L.push(story(12,"animal-island","井井有条","看画面理解成语","哪个书桌摆放得整齐有顺序","井井有条。Organized!",["井井有条","organized"],[{id:"messy",emoji:"📚🧦🖍️💥",label:"乱成一团"},{id:"empty",emoji:"🪹",label:"什么也没有"},{id:"order",emoji:"📚📒✏️✅",label:"分类摆整齐"}],"order","井井有条，就是整齐而有顺序。Organized!","你理解了 井井有条 (organized) 🗂️","🗂️ 书架整理好了"));
L.push(story(13,"animal-island","助人为乐","看故事理解成语","哪个孩子主动帮助了别人","助人为乐。Help others!",["助人为乐","help"],[{id:"ignore",emoji:"🙈",label:"假装没看见"},{id:"help",emoji:"🧒🤝👧",label:"扶起摔倒的同学"},{id:"take",emoji:"🧒🍪🍪",label:"拿走两块饼干"}],"help","助人为乐，帮助别人并感到快乐。Help others!","你理解了 助人为乐 (help) 🤝","🤝 互助桥出现了"));
L.push(story(14,"animal-island","画龙点睛","看故事理解成语","哪一步让整幅画一下子有了精神","画龙点睛。The finishing touch!",["画龙点睛","finishing touch"],[{id:"paper",emoji:"📄",label:"拿出一张白纸"},{id:"color",emoji:"🎨",label:"准备许多颜料"},{id:"eyes",emoji:"🐉👀✨",label:"给龙画上眼睛"}],"eyes","画龙点睛，加上最重要的一笔。The finishing touch!","你理解了 画龙点睛 (finishing touch) 🐉","🐉 龙睁开了眼睛"));
L.push(story(15,"animal-island","守株待兔","看画面理解成语","哪个人在傻等好运气","守株待兔。Don't just wait!",["守株待兔","wait"],[{id:"work",emoji:"🧒🌾💪",label:"努力干活"},{id:"wait",emoji:"🧒🌳🐰💤",label:"坐在树桩旁傻等"},{id:"play",emoji:"🧒⚽😄",label:"开心玩耍"}],"wait","守株待兔，不要傻等好运气。Don't just wait!","你理解了 守株待兔 (wait)","🌳 树桩旁边"));
L.push(story(16,"animal-island","亡羊补牢","看故事理解成语","出了问题后应该怎么做","亡羊补牢。Fix it in time!",["亡羊补牢","fix"],[{id:"cry",emoji:"😭🐑",label:"只哭不修"},{id:"fix",emoji:"🧑‍🔧🐑✅",label:"赶紧修补羊圈"},{id:"ignore",emoji:"🙈🐑",label:"假装没事"}],"fix","亡羊补牢，出了问题及时补救。Fix it in time!","你理解了 亡羊补牢 (fix)","🛠️ 羊圈修好了"));
L.push(choice(17,"animal-island","狐假虎威","看画面理解成语","哪个是狐假虎威？(英文关键词：pretend)","狐假虎威。Pretend to be powerful!",["狐假虎威","pretend"],[{id:"brave",emoji:"🧒💪",label:"自己勇敢 brave"},{id:"pretend",emoji:"🦊🐯😨",label:"狐假虎威 pretend"},{id:"kind",emoji:"🧒🤝",label:"善良 kind"}],"pretend","狐假虎威，借别人的威风吓人。Pretend!","你理解了 狐假虎威 (pretend)","🦊 狐狸的故事"));
L.push(choice(18,"animal-island","对牛弹琴","看画面理解成语","哪个是对牛弹琴？(英文关键词：waste)","对牛弹琴。Waste of effort!",["对牛弹琴","waste"],[{id:"teach",emoji:"👩‍🏫👧✅",label:"教同学学习"},{id:"waste",emoji:"🎵🐄❓",label:"对牛弹琴 waste"},{id:"sing",emoji:"🎤😄",label:"开心唱歌"}],"waste","对牛弹琴，对不懂的人讲没用。Waste of effort!","你理解了 对牛弹琴 (waste)","🐄 牛牛困惑了"));
L.push(story(19,"animal-island","坐井观天","看画面理解成语","哪个是坐井观天？(英文关键词：narrow view)","坐井观天。Narrow view!",["坐井观天","narrow view"],[{id:"travel",emoji:"🌍✈️😄",label:"到处旅行长见识"},{id:"narrow",emoji:"🐸🕳️👀",label:"坐在井里看天"},{id:"read",emoji:"📚👧",label:"读书学习"}],"narrow","坐井观天，眼界太窄。Narrow view!","你理解了 坐井观天 (narrow view)","🕳️ 青蛙出井了"));
L.push(boss(20,"animal-island","动物成语大挑战","四项成语综合","完成四项成语任务","成语大闯关！",["一心一意","井井有条","助人为乐","画龙点睛"],[{type:"choice",instruction:"哪个是 一心一意",prompt:"一心一意",answer:"focus",options:[{id:"messy",emoji:"📚💥",label:"乱七八糟"},{id:"focus",emoji:"🧒📖✨",label:"一心一意 focus"},{id:"lazy",emoji:"🛌💤",label:"懒洋洋"}]},{type:"choice",instruction:"哪个是 井井有条",prompt:"井井有条",answer:"order",options:[{id:"messy2",emoji:"🧦💥📚",label:"乱七八糟"},{id:"order",emoji:"📚📒✅",label:"井井有条 organized"},{id:"empty",emoji:"🪹",label:"空的"}]},{type:"choice",instruction:"哪个是 助人为乐",prompt:"助人为乐",answer:"help",options:[{id:"selfish",emoji:"🙈",label:"不管别人"},{id:"help",emoji:"🧒🤝👧",label:"助人为乐 help"},{id:"laugh",emoji:"🤣",label:"嘲笑别人"}]},{type:"choice",instruction:"哪个是 画龙点睛",prompt:"画龙点睛",answer:"eyes",options:[{id:"paper",emoji:"📄",label:"白纸"},{id:"eyes",emoji:"🐉👀✨",label:"画龙点睛 touch"},{id:"tail",emoji:"🐉🎨",label:"画尾巴"}]}],"太棒了！动物成语全部通关！","你掌握了动物成语四题","动物成语通关！","🏆 动物成语勋章"));

// ===== 校园岛 英语 (21-30) =====
L.push(choice(21,"school-island","找到书本","听单词选物品","听到口令后，选择正确的","Find the book.",["book"],[{id:"pencil",emoji:"✏️",label:"pencil"},{id:"book",emoji:"📘",label:"book"},{id:"bag",emoji:"🎒",label:"bag"}],"book","Yes! Book! 📘","你听懂了 book","📚 课本出现了"));
L.push(choice(22,"school-island","找到铅笔","听单词选物品","听到口令后，选择正确的","Find the pencil.",["pencil"],[{id:"book",emoji:"📘",label:"book"},{id:"pencil",emoji:"✏️",label:"pencil"},{id:"ruler",emoji:"📏",label:"ruler"}],"pencil","Yes! Pencil! ✏️","你听懂了 pencil","✏️ 铅笔出现了"));
L.push(choice(23,"school-island","找到书包","听单词选物品","听到口令后，选择正确的","Find the bag.",["bag"],[{id:"book",emoji:"📘",label:"book"},{id:"eraser",emoji:"🧽",label:"eraser"},{id:"bag",emoji:"🎒",label:"bag"}],"bag","Yes! Bag! 🎒","你听懂了 bag","🎒 书包出现了"));
L.push(choice(24,"school-island","老师好","听音选场景","听到口令后，选择正确的场景","Good morning, teacher!",["good morning","teacher"],[{id:"playground",emoji:"⚽🏃",label:"playground"},{id:"classroom",emoji:"🏫👋",label:"greet teacher"},{id:"lunch",emoji:"🍽️",label:"lunch time"}],"classroom","Yes! Good morning, teacher!","你听懂了 Good morning, teacher!","🏫 校门打开了"));
L.push(story(25,"school-island","我可以进来吗","听句子选场景","听句子，选择它描述的画面","May I come in?",["may I come in"],[{id:"go-out",emoji:"🚶‍♀️🚪",label:"going out"},{id:"come-in",emoji:"✋🚪🏫",label:"knocking to come in"},{id:"sit",emoji:"🪑",label:"sitting down"}],"come-in","Yes! May I come in?","你听懂了 May I come in?","🚪 门打开了"));
L.push(story(26,"school-island","谁在写字","听句子选场景","听句子，选择它描述的画面","I am writing.",["writing","I am"],[{id:"reading",emoji:"📖",label:"reading"},{id:"writing",emoji:"✏️📝",label:"writing"},{id:"drawing",emoji:"🎨",label:"drawing"}],"writing","Yes! I am writing!","你听懂了 I am writing","✏️ 写字板准备好了"));
L.push(wordForge(27,"school-island","拼出 BOOK","按顺序拼单词","按听到的顺序点字母","Build book. B. O. O. K. Book.",["book","b","o","k"],["O","K","B"],"BOOK","Yes! B. O. O. K. Book!","你拼出了 BOOK","📘 书本拼好了"));
L.push(echo(28,"school-island","跟读：谢谢老师","听示范并跟读","听完示范，再说同一句话","Thank you, teacher.",["thank you","teacher"],["thank you teacher","thank you","teacher"],"You're welcome!","你说出了 Thank you, teacher!","🙏 感谢手势"));
L.push(choice(29,"school-island","找到尺子","听单词选物品","听到口令后，选择正确的","Find the ruler.",["ruler"],[{id:"pencil",emoji:"✏️",label:"pencil"},{id:"eraser",emoji:"🧽",label:"eraser"},{id:"ruler",emoji:"📏",label:"ruler"}],"ruler","Yes! Ruler! 📏","你听懂了 ruler","📏 尺子出现了"));
L.push(boss(30,"school-island","校园岛 Boss","四项综合任务","完成四项任务，点亮校园岛","Let's save School Island!",["book","pencil","teacher","ruler"],[{type:"choice",instruction:"选择书本",prompt:"Find the book.",answer:"book",options:[{id:"pencil",emoji:"✏️",label:"pencil"},{id:"book",emoji:"📘",label:"book"},{id:"bag",emoji:"🎒",label:"bag"}]},{type:"word-forge",instruction:"拼出 PEN",prompt:"Build pen. P. E. N.",answer:"PEN",letters:["E","N","P"]},{type:"choice",instruction:"选择老师",prompt:"Find the teacher.",answer:"teacher",options:[{id:"student",emoji:"👧",label:"student"},{id:"teacher",emoji:"👩‍🏫",label:"teacher"},{id:"dog",emoji:"🐶",label:"dog"}]},{type:"echo",instruction:"跟读句子",prompt:"Good morning, teacher!",accepted:["good morning teacher","good morning","morning teacher"]}],"School Island is saved!","你完成了校园岛的所有挑战","校园岛得救了！","✨ 校园岛完全修复"));

// ===== 校园岛 成语 (31-40) =====
L.push(story(31,"school-island","不耻下问","看画面理解成语","哪个孩子在勇敢提问","不耻下问。Ask questions!",["不耻下问","ask"],[{id:"shy",emoji:"🧒😶",label:"不敢提问"},{id:"ask",emoji:"🧒✋👩‍🏫",label:"勇敢举手提问"},{id:"sleep",emoji:"🧒😴",label:"上课睡觉"}],"ask","不耻下问，不懂就问。Ask questions!","你理解了 不耻下问 (ask)","✋ 勇敢提问星"));
L.push(story(32,"school-island","举一反三","看画面理解成语","哪个孩子学一个会三个","举一反三。Learn one, know three!",["举一反三","learn"],[{id:"copy",emoji:"🧒📝📝",label:"只会抄写"},{id:"learn",emoji:"🧒💡3️⃣",label:"学一个会三个"},{id:"forget",emoji:"🧒🤷",label:"学完就忘"}],"learn","举一反三，学一个能推出更多。Learn one, know three!","你理解了 举一反三 (learn)","💡 灵感灯泡"));
L.push(story(33,"school-island","温故知新","看画面理解成语","哪个孩子在复习旧知识学到新东西","温故知新。Review and learn new!",["温故知新","review"],[{id:"skip",emoji:"🧒⏭️",label:"跳过复习"},{id:"review",emoji:"🧒📖✨💡",label:"复习后有了新发现"},{id:"cram",emoji:"🧒📚😰",label:"临时抱佛脚"}],"review","温故知新，复习旧知识得到新理解。Review and learn new!","你理解了 温故知新 (review)","📖 复习书打开了"));
L.push(story(34,"school-island","学而不厌","看画面理解成语","哪个孩子一直想学更多","学而不厌。Never tired of learning!",["学而不厌","learning"],[{id:"bored",emoji:"🧒🥱📚",label:"学习很烦"},{id:"learning",emoji:"🧒📚😊➡️📖",label:"一直快乐学习"},{id:"play",emoji:"🧒🎮",label:"只想玩"}],"learning","学而不厌，学习永远不嫌多。Never tired of learning!","你理解了 学而不厌 (learning)","📚 知识树长高了"));
L.push(story(35,"school-island","循序渐进","看画面理解成语","哪种学习方法是对的","循序渐进。Step by step!",["循序渐进","step"],[{id:"rush",emoji:"🧒🏃💨📚",label:"急急忙忙跳着学"},{id:"step",emoji:"🧒1️⃣2️⃣3️⃣📚",label:"一步一步慢慢来"},{id:"stop",emoji:"🧒🛑",label:"中途放弃"}],"step","循序渐进，一步一步来。Step by step!","你理解了 循序渐进 (step)","🪜 进步阶梯"));
L.push(story(36,"school-island","半途而废","看画面理解成语","哪个孩子中途放弃了","半途而废。Don't give up halfway!",["半途而废","give up"],[{id:"finish",emoji:"🧒🏁✅",label:"坚持到底完成"},{id:"giveup",emoji:"🧒🛑😢",label:"做到一半放弃了"},{id:"start",emoji:"🧒🚀",label:"刚开始"}],"giveup","半途而废，做到一半就放弃。Don't give up!","你理解了 半途而废 (give up)","🛑 不要放弃"));
L.push(choice(37,"school-island","业精于勤","看画面理解成语","哪个说明业精于勤？(英文关键词：diligent)","业精于勤。Diligent!",["业精于勤","diligent"],[{id:"lazy",emoji:"🧒🛌📚",label:"偷懒不学 lazy"},{id:"diligent",emoji:"🧒📝💪✨",label:"勤奋练习 diligent"},{id:"copy",emoji:"🧒📋",label:"抄答案"}],"diligent","业精于勤，勤奋才能学好。Diligent!","你理解了 业精于勤 (diligent)","💪 勤奋星"));
L.push(choice(38,"school-island","开卷有益","看画面理解成语","哪个说明开卷有益？(英文关键词：reading helps)","开卷有益。Reading helps!",["开卷有益","reading"],[{id:"reading",emoji:"🧒📖✨💡",label:"读书有收获 reading"},{id:"waste",emoji:"🧒📺😰",label:"浪费时间"},{id:"bored",emoji:"🧒📖🥱",label:"读书无聊"}],"reading","开卷有益，读书总是有好处的。Reading helps!","你理解了 开卷有益 (reading)","📖 好书发光了"));
L.push(story(39,"school-island","笨鸟先飞","看画面理解成语","哪个说明笨鸟先飞","笨鸟先飞。Start early to succeed!",["笨鸟先飞","early"],[{id:"early",emoji:"🐦⏰💪✨",label:"早起多练先出发"},{id:"late",emoji:"🐦😴⏰",label:"睡懒觉迟到"},{id:"giveup",emoji:"🐦😢",label:"放弃不练"}],"early","笨鸟先飞，先出发先努力。Start early!","你理解了 笨鸟先飞 (early)","🐦 早起的鸟儿"));
L.push(boss(40,"school-island","校园成语大挑战","四项成语综合","完成四项成语任务","校园成语大闯关！",["不耻下问","举一反三","循序渐进","笨鸟先飞"],[{type:"choice",instruction:"哪个是 不耻下问",prompt:"不耻下问",answer:"ask",options:[{id:"shy",emoji:"🧒😶",label:"不敢问"},{id:"ask",emoji:"🧒✋👩‍🏫",label:"不耻下问 ask"},{id:"sleep",emoji:"🧒😴",label:"睡觉"}]},{type:"choice",instruction:"哪个是 举一反三",prompt:"举一反三",answer:"learn",options:[{id:"copy",emoji:"🧒📝",label:"抄写"},{id:"learn",emoji:"🧒💡3️⃣",label:"举一反三 learn"},{id:"forget",emoji:"🧒🤷",label:"忘了"}]},{type:"choice",instruction:"哪个是 循序渐进",prompt:"循序渐进",answer:"step",options:[{id:"rush",emoji:"🏃💨",label:"急急忙忙"},{id:"step",emoji:"1️⃣2️⃣3️⃣",label:"循序渐进 step"},{id:"stop",emoji:"🛑",label:"放弃"}]},{type:"choice",instruction:"哪个是 笨鸟先飞",prompt:"笨鸟先飞",answer:"early",options:[{id:"early",emoji:"🐦⏰✨",label:"笨鸟先飞 early"},{id:"late",emoji:"🐦😴",label:"睡懒觉"},{id:"quit",emoji:"🐦😢",label:"放弃"}]}],"太棒了！校园成语全部通关！","你掌握了校园成语四题","校园成语通关！","🏆 校园成语勋章"));

// ===== 生活岛 英语 (41-50) =====
L.push(choice(41,"life-island","找到牛奶","听单词选物品","听到口令后，选择正确的","Find the milk.",["milk"],[{id:"water",emoji:"💧",label:"water"},{id:"milk",emoji:"🥛",label:"milk"},{id:"juice",emoji:"🧃",label:"juice"}],"milk","Yes! Milk! 🥛","你听懂了 milk","🥛 牛奶出现了"));
L.push(choice(42,"life-island","找到水","听单词选物品","听到口令后，选择正确的","Find the water.",["water"],[{id:"milk",emoji:"🥛",label:"milk"},{id:"juice",emoji:"🧃",label:"juice"},{id:"water",emoji:"💧",label:"water"}],"water","Yes! Water! 💧","你听懂了 water","💧 水杯出现了"));
L.push(choice(43,"life-island","找到鞋子","听单词选物品","听到口令后，选择正确的","Find the shoes.",["shoes"],[{id:"hat",emoji:"🧢",label:"hat"},{id:"shoes",emoji:"👟",label:"shoes"},{id:"coat",emoji:"🧥",label:"coat"}],"shoes","Yes! Shoes! 👟","你听懂了 shoes","👟 鞋子出现了"));
L.push(choice(44,"life-island","找到帽子","听单词选物品","听到口令后，选择正确的","Find the hat.",["hat"],[{id:"shoes",emoji:"👟",label:"shoes"},{id:"coat",emoji:"🧥",label:"coat"},{id:"hat",emoji:"🧢",label:"hat"}],"hat","Yes! Hat! 🧢","你听懂了 hat","🧢 帽子出现了"));
L.push(story(45,"life-island","穿上外套","听句子选场景","听句子，选择它描述的画面","Put on your coat.",["put on","coat"],[{id:"take-off",emoji:"🧥❌",label:"take off coat"},{id:"put-on",emoji:"🧥✅👧",label:"put on coat"},{id:"wash",emoji:"🧥🧼",label:"wash coat"}],"put-on","Yes! Put on your coat!","你听懂了 Put on your coat","🧥 外套穿好了"));
L.push(story(46,"life-island","我找不到","听句子选场景","听句子，选择它描述的画面","I can't find my bag.",["can't find","bag"],[{id:"found",emoji:"🎒😊",label:"found the bag"},{id:"lost",emoji:"🧒🤷🎒❓",label:"can't find the bag"},{id:"open",emoji:"🎒📂",label:"opening the bag"}],"lost","Yes! I can't find my bag!","你听懂了 I can't find my bag","🎒 书包找到了"));
L.push(wordForge(47,"life-island","拼出 MILK","按顺序拼单词","按听到的顺序点字母","Build milk. M. I. L. K. Milk.",["milk","m","i","l","k"],["I","K","M","L"],"MILK","Yes! M. I. L. K. Milk!","你拼出了 MILK","🥛 牛奶拼好了"));
L.push(echo(48,"life-island","跟读：再见","听示范并跟读","听完示范，再说同一句话","Goodbye!",["goodbye"],["goodbye","bye","see you"],"Goodbye! See you soon!","你说出了 Goodbye!","👋 挥手告别"));
L.push(choice(49,"life-island","找到果汁","听单词选物品","听到口令后，选择正确的","Find the juice.",["juice"],[{id:"milk",emoji:"🥛",label:"milk"},{id:"water",emoji:"💧",label:"water"},{id:"juice",emoji:"🧃",label:"juice"}],"juice","Yes! Juice! 🧃","你听懂了 juice","🧃 果汁出现了"));
L.push(boss(50,"life-island","生活岛 Boss","四项综合任务","完成四项任务，点亮生活岛","Let's save Life Island!",["milk","shoes","hat","coat"],[{type:"choice",instruction:"选择牛奶",prompt:"Find the milk.",answer:"milk",options:[{id:"water",emoji:"💧",label:"water"},{id:"milk",emoji:"🥛",label:"milk"},{id:"juice",emoji:"🧃",label:"juice"}]},{type:"word-forge",instruction:"拼出 HAT",prompt:"Build hat. H. A. T.",answer:"HAT",letters:["T","H","A"]},{type:"choice",instruction:"选择鞋子",prompt:"Find the shoes.",answer:"shoes",options:[{id:"hat",emoji:"🧢",label:"hat"},{id:"shoes",emoji:"👟",label:"shoes"},{id:"coat",emoji:"🧥",label:"coat"}]},{type:"echo",instruction:"跟读句子",prompt:"Put on your coat.",accepted:["put on your coat","put on coat","your coat"]}],"Life Island is saved!","你完成了生活岛的所有挑战","生活岛得救了！","✨ 生活岛完全修复"));

// ===== 生活岛 成语 (51-60) =====
L.push(story(51,"life-island","一诺千金","看画面理解成语","哪个孩子说话算数","一诺千金。Keep your promise!",["一诺千金","promise"],[{id:"break",emoji:"🧒🤞💔",label:"说话不算数"},{id:"promise",emoji:"🧒🤝✨",label:"说到做到"},{id:"forget",emoji:"🧒🤷",label:"忘了答应的事"}],"promise","一诺千金，承诺很值钱。Keep your promise!","你理解了 一诺千金 (promise)","🤝 诚信勋章"));
L.push(story(52,"life-island","言而有信","看画面理解成语","哪个是言而有信","言而有信。Honest and trustworthy!",["言而有信","honest"],[{id:"lie",emoji:"🧒🤥",label:"说谎话"},{id:"honest",emoji:"🧒✅💖",label:"说话算数"},{id:"late",emoji:"🧒⏰😰",label:"总是迟到"}],"honest","言而有信，说话讲信用。Honest!","你理解了 言而有信 (honest)","✅ 诚信章"));
L.push(story(53,"life-island","知足常乐","看画面理解成语","哪个孩子知足常乐","知足常乐。Be happy with what you have!",["知足常乐","content"],[{id:"greedy",emoji:"🧒🍪🍪🍪😰",label:"总想要更多"},{id:"content",emoji:"🧒🍪😊",label:"有一个就很开心"},{id:"sad",emoji:"🧒😢",label:"什么都不开心"}],"content","知足常乐，满足就快乐。Be happy with what you have!","你理解了 知足常乐 (content)","😊 满足星"));
L.push(story(54,"life-island","精打细算","看画面理解成语","哪个是精打细算","精打细算。Save carefully!",["精打细算","save"],[{id:"waste",emoji:"🧒💰💥",label:"乱花钱"},{id:"save",emoji:"🧒💰📝✅",label:"仔细计算着花"},{id:"steal",emoji:"🧒💰🤫",label:"偷钱"}],"save","精打细算，仔细计算不浪费。Save carefully!","你理解了 精打细算 (save)","💰 省钱罐"));
L.push(story(55,"life-island","未雨绸缪","看画面理解成语","哪个是未雨绸缪","未雨绸缪。Prepare before it rains!",["未雨绸缪","prepare"],[{id:"wet",emoji:"🧒🌧️😰",label:"下雨淋湿了"},{id:"prepare",emoji:"🧒☂️☁️✅",label:"提前带伞出门"},{id:"rain",emoji:"🧒🌧️🏠",label:"下雨待在家"}],"prepare","未雨绸缪，提前准备。Prepare before it rains!","你理解了 未雨绸缪 (prepare)","☂️ 伞准备好了"));
L.push(choice(56,"life-island","有备无患","看画面理解成语","哪个是有备无患？(英文关键词：prepared)","有备无患。Be prepared!",["有备无患","prepared"],[{id:"prepared",emoji:"🧒🎒✅😊",label:"提前准备有备无患"},{id:"worry",emoji:"🧒😰💥",label:"没有准备手忙脚乱"},{id:"lucky",emoji:"🧒🍀",label:"靠运气"}],"prepared","有备无患，有准备就不怕。Be prepared!","你理解了 有备无患 (prepared)","🎒 准备好了"));
L.push(story(57,"life-island","防微杜渐","看画面理解成语","哪个是防微杜渐","防微杜渐。Fix small problems early!",["防微杜渐","prevent"],[{id:"big",emoji:"🧒🐛💥😰",label:"小问题变成大问题"},{id:"prevent",emoji:"🧒🐜✅✨",label:"小问题早处理"},{id:"ignore",emoji:"🧒🙈",label:"假装看不见"}],"prevent","防微杜渐，小问题早点解决。Fix small problems early!","你理解了 防微杜渐 (prevent)","🔍 仔细检查"));
L.push(choice(58,"life-island","因地制宜","看画面理解成语","哪个是因地制宜？(英文关键词：adapt)","因地制宜。Adapt to the situation!",["因地制宜","adapt"],[{id:"same",emoji:"🧒📋❌",label:"所有地方用一样的方法"},{id:"adapt",emoji:"🧒🏔️🌾🏖️✅",label:"根据不同地方调整"},{id:"copy",emoji:"🧒📋📋",label:"照抄别人"}],"adapt","因地制宜，根据实际情况来。Adapt!","你理解了 因地制宜 (adapt)","🗺️ 适应地图"));
L.push(story(59,"life-island","居安思危","看画面理解成语","哪个是居安思危","居安思危。Think of danger in peace!",["居安思危","cautious"],[{id:"relax",emoji:"🧒🏖️😊💤",label:"太安逸忘了危险"},{id:"cautious",emoji:"🧒🏠⚠️✅",label:"安全时也想危险"},{id:"scared",emoji:"🧒😨",label:"总是害怕"}],"cautious","居安思危，安全时也想到危险。Be cautious!","你理解了 居安思危 (cautious)","⚠️ 安全意识"));
L.push(boss(60,"life-island","生活成语大挑战","四项成语综合","完成四项成语任务","生活成语大闯关！",["一诺千金","知足常乐","未雨绸缪","有备无患"],[{type:"choice",instruction:"哪个是 一诺千金",prompt:"一诺千金",answer:"promise",options:[{id:"break",emoji:"🤞💔",label:"说话不算数"},{id:"promise",emoji:"🤝✨",label:"一诺千金 promise"},{id:"forget",emoji:"🤷",label:"忘了"}]},{type:"choice",instruction:"哪个是 知足常乐",prompt:"知足常乐",answer:"content",options:[{id:"greedy",emoji:"🍪🍪😰",label:"贪心"},{id:"content",emoji:"🍪😊",label:"知足常乐 content"},{id:"sad",emoji:"😢",label:"难过"}]},{type:"choice",instruction:"哪个是 未雨绸缪",prompt:"未雨绸缪",answer:"prepare",options:[{id:"wet",emoji:"🌧️😰",label:"淋湿了"},{id:"prepare",emoji:"☂️✅",label:"未雨绸缪 prepare"},{id:"home",emoji:"🏠",label:"待在家"}]},{type:"choice",instruction:"哪个是 有备无患",prompt:"有备无患",answer:"prepared",options:[{id:"prepared",emoji:"🎒✅",label:"有备无患 prepared"},{id:"worry",emoji:"😰💥",label:"手忙脚乱"},{id:"lucky",emoji:"🍀",label:"靠运气"}]}],"太棒了！生活成语全部通关！","你掌握了生活成语四题","生活成语通关！","🏆 生活成语勋章"));

// ===== 美食岛 英语 (61-70) =====
L.push(choice(61,"food-island","找到蛋糕","听单词选食物","听到口令后，选择正确的","Find the cake.",["cake"],[{id:"bread",emoji:"🍞",label:"bread"},{id:"cake",emoji:"🍰",label:"cake"},{id:"rice",emoji:"🍚",label:"rice"}],"cake","Yes! Cake! 🍰","你听懂了 cake","🍰 蛋糕出现了"));
L.push(choice(62,"food-island","找到面包","听单词选食物","听到口令后，选择正确的","Find the bread.",["bread"],[{id:"cake",emoji:"🍰",label:"cake"},{id:"egg",emoji:"🥚",label:"egg"},{id:"bread",emoji:"🍞",label:"bread"}],"bread","Yes! Bread! 🍞","你听懂了 bread","🍞 面包出现了"));
L.push(choice(63,"food-island","找到苹果","听单词选食物","听到口令后，选择正确的","Find the apple.",["apple"],[{id:"banana",emoji:"🍌",label:"banana"},{id:"apple",emoji:"🍎",label:"apple"},{id:"candy",emoji:"🍬",label:"candy"}],"apple","Yes! Apple! 🍎","你听懂了 apple","🍎 苹果出现了"));
L.push(choice(64,"food-island","找到香蕉","听单词选食物","听到口令后，选择正确的","Find the banana.",["banana"],[{id:"apple",emoji:"🍎",label:"apple"},{id:"pizza",emoji:"🍕",label:"pizza"},{id:"banana",emoji:"🍌",label:"banana"}],"banana","Yes! Banana! 🍌","你听懂了 banana","🍌 香蕉出现了"));
L.push(story(65,"food-island","我想要","听句子选场景","听句子，选择它描述的画面","I would like some rice.",["I would like","rice"],[{id:"cake",emoji:"🍰🙋",label:"want cake"},{id:"rice",emoji:"🍚🙋",label:"want rice"},{id:"bread",emoji:"🍞🙋",label:"want bread"}],"rice","Yes! I would like some rice!","你听懂了 I would like some rice","🍚 米饭出现了"));
L.push(story(66,"food-island","我能要吗","听句子选场景","听句子，选择它描述的画面","Can I have some water?",["Can I have","water"],[{id:"juice",emoji:"🧃🙋",label:"ask for juice"},{id:"water",emoji:"💧🙋",label:"ask for water"},{id:"milk",emoji:"🥛🙋",label:"ask for milk"}],"water","Yes! Can I have some water?","你听懂了 Can I have some water?","💧 水来了"));
L.push(wordForge(67,"food-island","拼出 CAKE","按顺序拼单词","按听到的顺序点字母","Build cake. C. A. K. E. Cake.",["cake","c","a","k","e"],["E","K","A","C"],"CAKE","Yes! C. A. K. E. Cake!","你拼出了 CAKE","🍰 蛋糕拼好了"));
L.push(echo(68,"food-island","跟读：我饿了","听示范并跟读","听完示范，再说同一句话","I am hungry.",["hungry","I am"],["i am hungry","am hungry","hungry"],"Let's eat something!","你说出了 I am hungry","🍽️ 餐桌准备好了"));
L.push(choice(69,"food-island","找到披萨","听单词选食物","听到口令后，选择正确的","Find the pizza.",["pizza"],[{id:"bread",emoji:"🍞",label:"bread"},{id:"cake",emoji:"🍰",label:"cake"},{id:"pizza",emoji:"🍕",label:"pizza"}],"pizza","Yes! Pizza! 🍕","你听懂了 pizza","🍕 披萨出现了"));
L.push(boss(70,"food-island","美食岛 Boss","四项综合任务","完成四项任务，点亮美食岛","Let's save Food Island!",["cake","bread","apple","pizza"],[{type:"choice",instruction:"选择蛋糕",prompt:"Find the cake.",answer:"cake",options:[{id:"bread",emoji:"🍞",label:"bread"},{id:"cake",emoji:"🍰",label:"cake"},{id:"rice",emoji:"🍚",label:"rice"}]},{type:"word-forge",instruction:"拼出 RICE",prompt:"Build rice. R. I. C. E.",answer:"RICE",letters:["E","C","I","R"]},{type:"choice",instruction:"选择苹果",prompt:"Find the apple.",answer:"apple",options:[{id:"banana",emoji:"🍌",label:"banana"},{id:"apple",emoji:"🍎",label:"apple"},{id:"candy",emoji:"🍬",label:"candy"}]},{type:"echo",instruction:"跟读句子",prompt:"I would like some cake.",accepted:["i would like some cake","would like some cake","some cake"]}],"Food Island is saved!","你完成了美食岛的所有挑战","美食岛得救了！","✨ 美食岛完全修复"));

// ===== 美食岛 成语 (71-80) =====
L.push(story(71,"food-island","津津有味","看画面理解成语","哪个孩子吃得很香","津津有味。Eat with pleasure!",["津津有味","delicious"],[{id:"hate",emoji:"😖🥦",label:"不喜欢吃"},{id:"enjoy",emoji:"👧😋🍕",label:"吃得很香"},{id:"full",emoji:"🥵🍽️",label:"吃饱了"}],"enjoy","津津有味，吃得非常香。Delicious!","你理解了 津津有味 (delicious)","😋 美味星"));
L.push(story(72,"food-island","狼吞虎咽","看画面理解成语","哪个是狼吞虎咽","狼吞虎咽。Eat very fast!",["狼吞虎咽","fast"],[{id:"slow",emoji:"🧒🍽️😊",label:"慢慢品尝"},{id:"fast",emoji:"🧒🍽️💨😰",label:"大口快速吞"},{id:"small",emoji:"🧒🥄",label:"小口小口吃"}],"fast","狼吞虎咽，吃得太快。Eat very fast!","你理解了 狼吞虎咽 (fast)","💨 快吃星"));
L.push(story(73,"food-island","丰衣足食","看画面理解成语","哪个是丰衣足食","丰衣足食。Have enough food and clothes!",["丰衣足食","enough"],[{id:"poor",emoji:"🧒🥶😰",label:"吃不饱穿不暖"},{id:"enough",emoji:"🧒👗🍽️😊",label:"吃穿都不愁"},{id:"waste",emoji:"🧒🍽️💥",label:"浪费粮食"}],"enough","丰衣足食，吃穿都不愁。Have enough!","你理解了 丰衣足食 (enough)","👗🍽️ 丰衣足食"));
L.push(story(74,"food-island","粗茶淡饭","看画面理解成语","哪个是粗茶淡饭","粗茶淡饭。Simple food!",["粗茶淡饭","simple"],[{id:"fancy",emoji:"🧒🦞🍰🍷",label:"豪华大餐"},{id:"simple",emoji:"🧒🍵🍚😊",label:"简单饭菜也满足"},{id:"no",emoji:"🧒😰",label:"没有饭吃"}],"simple","粗茶淡饭，简单朴素。Simple food!","你理解了 粗茶淡饭 (simple)","🍵 清茶淡饭"));
L.push(story(75,"food-island","饮水思源","看画面理解成语","哪个是饮水思源","饮水思源。Remember the source!",["饮水思源","grateful"],[{id:"forget",emoji:"🧒💧🤷",label:"喝水忘了水源"},{id:"grateful",emoji:"🧒💧🙏✨",label:"喝水不忘来源"},{id:"waste",emoji:"🧒💧💥",label:"浪费水"}],"grateful","饮水思源，不忘本。Be grateful!","你理解了 饮水思源 (grateful)","💧 感恩水滴"));
L.push(story(76,"food-island","粒粒皆辛苦","看画面理解成语","哪个是粒粒皆辛苦","粒粒皆辛苦。Every grain is hard work!",["粒粒皆辛苦","hard work"],[{id:"waste",emoji:"🧒🍚💥",label:"浪费粮食"},{id:"cherish",emoji:"🧒🌾🍚🙏",label:"珍惜每一粒米"},{id:"pick",emoji:"🧒🍚❌",label:"挑食不吃"}],"cherish","粒粒皆辛苦，珍惜粮食。Every grain is hard work!","你理解了 粒粒皆辛苦 (hard work)","🌾 珍惜粮食"));
L.push(choice(77,"food-island","甜言蜜语","看画面理解成语","哪个是甜言蜜语？(英文关键词：sweet words)","甜言蜜语。Sweet words!",["甜言蜜语","sweet words"],[{id:"honest",emoji:"🧒💬✅",label:"说实话 honest"},{id:"sweet",emoji:"🧒🍬💬😏",label:"甜言蜜语 sweet words"},{id:"mean",emoji:"🧒😡💬",label:"说坏话"}],"sweet","甜言蜜语，好听但不一定真心。Sweet words!","你理解了 甜言蜜语 (sweet words)","🍬 甜蜜语言"));
L.push(story(78,"food-island","苦尽甘来","看画面理解成语","哪个是苦尽甘来","苦尽甘来。After hardship comes happiness!",["苦尽甘来","sweet after bitter"],[{id:"bitter",emoji:"🧒😰➡️😰",label:"一直苦"},{id:"sweet",emoji:"🧒😰➡️😊✨",label:"先苦后甜"},{id:"easy",emoji:"🧒😊➡️😊",label:"一直轻松"}],"sweet","苦尽甘来，苦完后甜就来了。Sweet after bitter!","你理解了 苦尽甘来 (sweet after bitter)","🌈 苦尽甘来"));
L.push(choice(79,"food-island","五谷丰登","看画面理解成语","哪个是五谷丰登？(英文关键词：harvest)","五谷丰登。Good harvest!",["五谷丰登","harvest"],[{id:"dry",emoji:"🏜️🌾😰",label:"干旱歉收"},{id:"harvest",emoji:"🌾🌽🍚🍎✨",label:"丰收五谷丰登"},{id:"plant",emoji:"🌱🧒",label:"刚播种"}],"harvest","五谷丰登，粮食大丰收。Good harvest!","你理解了 五谷丰登 (harvest)","🌾 丰收节"));
L.push(boss(80,"food-island","美食成语大挑战","四项成语综合","完成四项成语任务","美食成语大闯关！",["津津有味","狼吞虎咽","饮水思源","苦尽甘来"],[{type:"choice",instruction:"哪个是 津津有味",prompt:"津津有味",answer:"enjoy",options:[{id:"hate",emoji:"😖🥦",label:"不喜欢"},{id:"enjoy",emoji:"😋🍕",label:"津津有味 delicious"},{id:"full",emoji:"🥵",label:"吃饱了"}]},{type:"choice",instruction:"哪个是 狼吞虎咽",prompt:"狼吞虎咽",answer:"fast",options:[{id:"slow",emoji:"🍽️😊",label:"慢慢吃"},{id:"fast",emoji:"🍽️💨",label:"狼吞虎咽 fast"},{id:"small",emoji:"🥄",label:"小口吃"}]},{type:"choice",instruction:"哪个是 饮水思源",prompt:"饮水思源",answer:"grateful",options:[{id:"forget",emoji:"💧🤷",label:"忘了来源"},{id:"grateful",emoji:"💧🙏",label:"饮水思源 grateful"},{id:"waste",emoji:"💧💥",label:"浪费"}]},{type:"choice",instruction:"哪个是 苦尽甘来",prompt:"苦尽甘来",answer:"sweet",options:[{id:"bitter",emoji:"😰➡️😰",label:"一直苦"},{id:"sweet",emoji:"😰➡️😊",label:"苦尽甘来"},{id:"easy",emoji:"😊➡️😊",label:"一直轻松"}]}],"太棒了！美食成语全部通关！","你掌握了美食成语四题","美食成语通关！","🏆 美食成语勋章"));

// ===== 情感岛 英语 (81-90) =====
L.push(choice(81,"feeling-island","找到开心","听音选情感","听到口令后，选择正确的表情","Find happy.",["happy"],[{id:"sad",emoji:"😢",label:"sad"},{id:"happy",emoji:"😄",label:"happy"},{id:"angry",emoji:"😡",label:"angry"}],"happy","Yes! Happy! 😄","你听懂了 happy","😄 开心出现了"));
L.push(choice(82,"feeling-island","找到难过","听音选情感","听到口令后，选择正确的表情","Find sad.",["sad"],[{id:"happy",emoji:"😄",label:"happy"},{id:"sad",emoji:"😢",label:"sad"},{id:"tired",emoji:"🥱",label:"tired"}],"sad","Yes! Sad! 😢","你听懂了 sad","😢 难过出现了"));
L.push(choice(83,"feeling-island","找到生气","听音选情感","听到口令后，选择正确的表情","Find angry.",["angry"],[{id:"happy",emoji:"😄",label:"happy"},{id:"scared",emoji:"😨",label:"scared"},{id:"angry",emoji:"😡",label:"angry"}],"angry","Yes! Angry! 😡","你听懂了 angry","😡 生气出现了"));
L.push(choice(84,"feeling-island","找到害怕","听音选情感","听到口令后，选择正确的表情","Find scared.",["scared"],[{id:"angry",emoji:"😡",label:"angry"},{id:"scared",emoji:"😨",label:"scared"},{id:"happy",emoji:"😄",label:"happy"}],"scared","Yes! Scared! 😨","你听懂了 scared","😨 害怕出现了"));
L.push(story(85,"feeling-island","我感觉很开心","听句子选场景","听句子，选择它描述的画面","I feel happy.",["I feel","happy"],[{id:"sad",emoji:"😢💔",label:"feeling sad"},{id:"happy",emoji:"😄🎉",label:"feeling happy"},{id:"tired",emoji:"🥱💤",label:"feeling tired"}],"happy","Yes! I feel happy!","你听懂了 I feel happy","🎉 开心气球"));
L.push(story(86,"feeling-island","你还好吗","听句子选场景","听句子，选择它描述的画面","Are you OK?",["Are you OK"],[{id:"hello",emoji:"👋😊",label:"saying hello"},{id:"ok",emoji:"🧒😢❓💕",label:"asking if OK"},{id:"bye",emoji:"👋",label:"saying goodbye"}],"ok","Yes! Are you OK?","你听懂了 Are you OK?","💕 关心来了"));
L.push(wordForge(87,"feeling-island","拼出 HAPPY","按顺序拼单词","按听到的顺序点字母","Build happy. H. A. P. P. Y. Happy.",["happy","h","a","p","y"],["Y","P","A","H","P"],"HAPPY","Yes! H. A. P. P. Y. Happy!","你拼出了 HAPPY","😄 开心拼好了"));
L.push(echo(88,"feeling-island","跟读：我很累","听示范并跟读","听完示范，再说同一句话","I am tired.",["tired","I am"],["i am tired","am tired","tired"],"Take a rest!","你说出了 I am tired","🛌 休息一下"));
L.push(choice(89,"feeling-island","找到紧张","听音选情感","听到口令后，选择正确的表情","Find nervous.",["nervous"],[{id:"happy",emoji:"😄",label:"happy"},{id:"nervous",emoji:"😰",label:"nervous"},{id:"angry",emoji:"😡",label:"angry"}],"nervous","Yes! Nervous! 😰","你听懂了 nervous","😰 紧张出现了"));
L.push(boss(90,"feeling-island","情感岛 Boss","四项综合任务","完成四项任务，点亮情感岛","Let's save Feeling Island!",["happy","sad","angry","scared"],[{type:"choice",instruction:"选择开心",prompt:"Find happy.",answer:"happy",options:[{id:"sad",emoji:"😢",label:"sad"},{id:"happy",emoji:"😄",label:"happy"},{id:"angry",emoji:"😡",label:"angry"}]},{type:"word-forge",instruction:"拼出 SAD",prompt:"Build sad. S. A. D.",answer:"SAD",letters:["D","A","S"]},{type:"choice",instruction:"选择害怕",prompt:"Find scared.",answer:"scared",options:[{id:"happy",emoji:"😄",label:"happy"},{id:"scared",emoji:"😨",label:"scared"},{id:"tired",emoji:"🥱",label:"tired"}]},{type:"echo",instruction:"跟读句子",prompt:"I feel happy.",accepted:["i feel happy","feel happy","happy"]}],"Feeling Island is saved!","你完成了情感岛的所有挑战","情感岛得救了！","✨ 情感岛完全修复"));

// ===== 情感岛 成语 (91-100) =====
L.push(story(91,"feeling-island","心花怒放","看画面理解成语","哪个孩子非常开心","心花怒放。Overjoyed!",["心花怒放","overjoyed"],[{id:"angry",emoji:"😡",label:"生气"},{id:"overjoyed",emoji:"👧🌸😄",label:"开心得像花开"},{id:"tired",emoji:"🥱",label:"疲惫"}],"overjoyed","心花怒放，心里高兴得像花儿开。Overjoyed!","你理解了 心花怒放 (overjoyed)","🌸 心花开了"));
L.push(story(92,"feeling-island","喜出望外","看画面理解成语","哪个是喜出望外","喜出望外。Pleasant surprise!",["喜出望外","surprise"],[{id:"expect",emoji:"🧒🎁😊",label:"收到期待的礼物"},{id:"surprise",emoji:"🧒🎁✨😲",label:"意外惊喜太开心"},{id:"disappoint",emoji:"🧒📦😰",label:"失望"}],"surprise","喜出望外，意外的惊喜。Surprise!","你理解了 喜出望外 (surprise)","✨ 惊喜星"));
L.push(story(93,"feeling-island","怒发冲冠","看画面理解成语","哪个是怒发冲冠","怒发冲冠。Very angry!",["怒发冲冠","furious"],[{id:"mild",emoji:"🧒😤",label:"有点不高兴"},{id:"furious",emoji:"🧒😡💨",label:"气得头发竖起来"},{id:"calm",emoji:"🧒😌",label:"很平静"}],"furious","怒发冲冠，气极了。Furious!","你理解了 怒发冲冠 (furious)","😡 愤怒火山"));
L.push(story(94,"feeling-island","胆小如鼠","看画面理解成语","哪个是胆小如鼠","胆小如鼠。As timid as a mouse!",["胆小如鼠","timid"],[{id:"brave",emoji:"🧒💪",label:"勇敢"},{id:"timid",emoji:"🧒🐭😰",label:"胆子很小"},{id:"happy",emoji:"🧒😊",label:"开心"}],"timid","胆小如鼠，胆子特别小。Timid!","你理解了 胆小如鼠 (timid)","🐭 小老鼠"));
L.push(story(95,"feeling-island","垂头丧气","看画面理解成语","哪个是垂头丧气","垂头丧气。Very discouraged!",["垂头丧气","discouraged"],[{id:"proud",emoji:"🧒😊💪",label:"很自豪"},{id:"discouraged",emoji:"🧒😔👇",label:"低着头很沮丧"},{id:"angry",emoji:"🧒😡",label:"生气"}],"discouraged","垂头丧气，非常沮丧。Discouraged!","你理解了 垂头丧气 (discouraged)","😔 鼓励星"));
L.push(choice(96,"feeling-island","欢天喜地","看画面理解成语","哪个是欢天喜地？(英文关键词：joyful)","欢天喜地。Joyful!",["欢天喜地","joyful"],[{id:"sad",emoji:"😢💔",label:"悲伤"},{id:"joyful",emoji:"😄🎉🎊✨",label:"欢天喜地 joyful"},{id:"calm",emoji:"😌",label:"平静"}],"joyful","欢天喜地，非常高兴。Joyful!","你理解了 欢天喜地 (joyful)","🎉 欢乐烟花"));
L.push(story(97,"feeling-island","心惊肉跳","看画面理解成语","哪个是心惊肉跳","心惊肉跳。Terrified!",["心惊肉跳","terrified"],[{id:"excited",emoji:"🧒😄💓",label:"兴奋"},{id:"terrified",emoji:"🧒😨💓💨",label:"害怕得心跳加速"},{id:"bored",emoji:"🧒🥱",label:"无聊"}],"terrified","心惊肉跳，害怕得心砰砰跳。Terrified!","你理解了 心惊肉跳 (terrified)","💓 心跳星"));
L.push(choice(98,"feeling-island","笑容可掬","看画面理解成语","哪个是笑容可掬？(英文关键词：beaming)","笑容可掬。Beaming with smiles!",["笑容可掬","beaming"],[{id:"frown",emoji:"😟",label:"皱眉"},{id:"beaming",emoji:"😊🤗✨",label:"笑容可掬 beaming"},{id:"cry",emoji:"😭",label:"哭泣"}],"beaming","笑容可掬，笑得满脸都是。Beaming!","你理解了 笑容可掬 (beaming)","😊 笑容星"));
L.push(story(99,"feeling-island","愁眉苦脸","看画面理解成语","哪个是愁眉苦脸","愁眉苦脸。Worried and sad!",["愁眉苦脸","worried"],[{id:"happy",emoji:"😄",label:"开心"},{id:"worried",emoji:"😟😢😖",label:"皱着眉头苦着脸"},{id:"think",emoji:"🤔",label:"思考"}],"worried","愁眉苦脸，愁眉不展。Worried!","你理解了 愁眉苦脸 (worried)","🌈 别愁了"));
L.push(boss(100,"feeling-island","情感成语大挑战","四项成语综合","完成四项成语任务","情感成语大闯关！",["心花怒放","喜出望外","垂头丧气","欢天喜地"],[{type:"choice",instruction:"哪个是 心花怒放",prompt:"心花怒放",answer:"overjoyed",options:[{id:"angry",emoji:"😡",label:"生气"},{id:"overjoyed",emoji:"🌸😄",label:"心花怒放 overjoyed"},{id:"tired",emoji:"🥱",label:"疲惫"}]},{type:"choice",instruction:"哪个是 喜出望外",prompt:"喜出望外",answer:"surprise",options:[{id:"expect",emoji:"🎁😊",label:"期待"},{id:"surprise",emoji:"🎁✨😲",label:"喜出望外 surprise"},{id:"sad",emoji:"📦😰",label:"失望"}]},{type:"choice",instruction:"哪个是 垂头丧气",prompt:"垂头丧气",answer:"discouraged",options:[{id:"proud",emoji:"😊💪",label:"自豪"},{id:"discouraged",emoji:"😔👇",label:"垂头丧气"},{id:"angry2",emoji:"😡",label:"生气"}]},{type:"choice",instruction:"哪个是 欢天喜地",prompt:"欢天喜地",answer:"joyful",options:[{id:"sad2",emoji:"😢",label:"悲伤"},{id:"joyful",emoji:"😄🎉",label:"欢天喜地 joyful"},{id:"calm",emoji:"😌",label:"平静"}]}],"太棒了！情感成语全部通关！","你掌握了情感成语四题","情感成语通关！","🏆 情感成语勋章"));

// ===== 自然岛 英语 (101-110) =====
L.push(choice(101,"nature-island","找到太阳","听单词选自然","听到口令后，选择正确的","Find the sun.",["sun"],[{id:"moon",emoji:"🌙",label:"moon"},{id:"sun",emoji:"☀️",label:"sun"},{id:"star",emoji:"⭐",label:"star"}],"sun","Yes! Sun! ☀️","你听懂了 sun","☀️ 太阳出现了"));
L.push(choice(102,"nature-island","找到月亮","听单词选自然","听到口令后，选择正确的","Find the moon.",["moon"],[{id:"sun",emoji:"☀️",label:"sun"},{id:"cloud",emoji:"☁️",label:"cloud"},{id:"moon",emoji:"🌙",label:"moon"}],"moon","Yes! Moon! 🌙","你听懂了 moon","🌙 月亮出现了"));
L.push(choice(103,"nature-island","找到花","听单词选自然","听到口令后，选择正确的","Find the flower.",["flower"],[{id:"tree",emoji:"🌳",label:"tree"},{id:"flower",emoji:"🌸",label:"flower"},{id:"rain",emoji:"🌧️",label:"rain"}],"flower","Yes! Flower! 🌸","你听懂了 flower","🌸 花儿出现了"));
L.push(choice(104,"nature-island","找到树","听单词选自然","听到口令后，选择正确的","Find the tree.",["tree"],[{id:"flower",emoji:"🌸",label:"flower"},{id:"cloud",emoji:"☁️",label:"cloud"},{id:"tree",emoji:"🌳",label:"tree"}],"tree","Yes! Tree! 🌳","你听懂了 tree","🌳 大树出现"));
L.push(story(105,"nature-island","下雨了","听句子选场景","听句子，选择它描述的画面","It is raining.",["raining","it is"],[{id:"sunny",emoji:"☀️😊",label:"sunny day"},{id:"rainy",emoji:"🌧️☔",label:"raining"},{id:"snowy",emoji:"❄️☃️",label:"snowing"}],"rainy","Yes! It is raining!","你听懂了 It is raining","🌧️ 下雨了"));
L.push(story(106,"nature-island","天气怎么样","听句子选场景","听句子，选择它描述的画面","What's the weather like?",["weather","what's the"],[{id:"ask",emoji:"🧒☁️❓",label:"asking about weather"},{id:"time",emoji:"🧒⏰❓",label:"asking about time"},{id:"food",emoji:"🧒🍕❓",label:"asking about food"}],"ask","Yes! What's the weather like?","你听懂了 What's the weather like?","🌤️ 天气站"));
L.push(wordForge(107,"nature-island","拼出 RAIN","按顺序拼单词","按听到的顺序点字母","Build rain. R. A. I. N. Rain.",["rain","r","a","i","n"],["I","N","A","R"],"RAIN","Yes! R. A. I. N. Rain!","你拼出了 RAIN","🌧️ 雨拼好了"));
L.push(echo(108,"nature-island","跟读：天在下雪","听示范并跟读","听完示范，再说同一句话","It is snowing.",["snowing","it is"],["it is snowing","is snowing","snowing"],"Let's make a snowman!","你说出了 It is snowing","☃️ 雪人出现了"));
L.push(choice(109,"nature-island","找到云","听单词选自然","听到口令后，选择正确的","Find the cloud.",["cloud"],[{id:"sun",emoji:"☀️",label:"sun"},{id:"rain",emoji:"🌧️",label:"rain"},{id:"cloud",emoji:"☁️",label:"cloud"}],"cloud","Yes! Cloud! ☁️","你听懂了 cloud","☁️ 云朵出现了"));
L.push(boss(110,"nature-island","自然岛 Boss","四项综合任务","完成四项任务，点亮自然岛","Let's save Nature Island!",["sun","rain","flower","tree"],[{type:"choice",instruction:"选择太阳",prompt:"Find the sun.",answer:"sun",options:[{id:"moon",emoji:"🌙",label:"moon"},{id:"sun",emoji:"☀️",label:"sun"},{id:"star",emoji:"⭐",label:"star"}]},{type:"word-forge",instruction:"拼出 TREE",prompt:"Build tree. T. R. E. E.",answer:"TREE",letters:["E","R","T","E"]},{type:"choice",instruction:"选择花",prompt:"Find the flower.",answer:"flower",options:[{id:"tree",emoji:"🌳",label:"tree"},{id:"flower",emoji:"🌸",label:"flower"},{id:"cloud",emoji:"☁️",label:"cloud"}]},{type:"echo",instruction:"跟读句子",prompt:"It is raining.",accepted:["it is raining","is raining","raining"]}],"Nature Island is saved!","你完成了自然岛的所有挑战","自然岛得救了！","✨ 自然岛完全修复"));

// ===== 自然岛 成语 (111-120) =====
L.push(story(111,"nature-island","风和日丽","看画面理解成语","哪个是风和日丽","风和日丽。Fine and warm!",["风和日丽","fine"],[{id:"storm",emoji:"⛈️💨😰",label:"狂风暴雨"},{id:"fine",emoji:"☀️🍃😊",label:"风和日丽天气好"},{id:"cold",emoji:"❄️🥶",label:"天寒地冻"}],"fine","风和日丽，天气晴朗和暖。Fine and warm!","你理解了 風和日丽 (fine)","☀️ 好天气"));
L.push(story(112,"nature-island","雨过天晴","看画面理解成语","哪个是雨过天晴","雨过天晴。Sun after rain!",["雨过天晴","clear after rain"],[{id:"rain",emoji:"🌧️☁️",label:"一直下雨"},{id:"clear",emoji:"🌧️➡️☀️🌈",label:"雨后出太阳"},{id:"dry",emoji:"☀️🏜️",label:"一直干旱"}],"clear","雨过天晴，雨后天气放晴。Sun after rain!","你理解了 雨过天晴 (clear after rain)","🌈 彩虹出现"));
L.push(story(113,"nature-island","鸟语花香","看画面理解成语","哪个是鸟语花香","鸟语花香。Birds sing, flowers bloom!",["鸟语花香","spring"],[{id:"winter",emoji:"❄️🌨️",label:"冬天"},{id:"spring",emoji:"🐦🌸🌳✨",label:"春天花园鸟语花香"},{id:"desert",emoji:"🏜️☀️",label:"沙漠"}],"spring","鸟语花香，春天生机勃勃。Birds sing, flowers bloom!","你理解了 鸟语花香 (spring)","🌸 花园盛开"));
L.push(story(114,"nature-island","山清水秀","看画面理解成语","哪个是山清水秀","山清水秀。Beautiful scenery!",["山清水秀","scenery"],[{id:"polluted",emoji:"🏭🌫️",label:"污染"},{id:"beautiful",emoji:"🏔️💧🌲✨",label:"青山绿水"},{id:"dry",emoji:"🏜️🌵",label:"干旱"}],"beautiful","山清水秀，风景优美。Beautiful scenery!","你理解了 山清水秀 (scenery)","🏔️ 山水美景"));
L.push(story(115,"nature-island","万紫千红","看画面理解成语","哪个是万紫千红","万紫千红。Colorful flowers everywhere!",["万紫千红","colorful"],[{id:"wilt",emoji:"🥀🍂",label:"花都枯萎了"},{id:"colorful",emoji:"🌸🌺🌻🌷💐",label:"百花盛开万紫千红"},{id:"one",emoji:"🌸",label:"只有一朵花"}],"colorful","万紫千红，花色繁多。Colorful!","你理解了 万紫千红 (colorful)","💐 百花齐放"));
L.push(choice(116,"nature-island","春暖花开","看画面理解成语","哪个是春暖花开？(英文关键词：spring blooms)","春暖花开。Spring blooms!",["春暖花开","spring blooms"],[{id:"snow",emoji:"❄️☃️",label:"下雪"},{id:"spring",emoji:"🌷🌱🐝✨",label:"春暖花开 spring"},{id:"autumn",emoji:"🍂🍁",label:"秋天"}],"spring","春暖花开，春天温暖花开。Spring blooms!","你理解了 春暖花开 (spring blooms)","🌷 春天来了"));
L.push(story(117,"nature-island","秋高气爽","看画面理解成语","哪个是秋高气爽","秋高气爽。Crisp autumn weather!",["秋高气爽","autumn"],[{id:"humid",emoji:"🥵💧",label:"闷热潮湿"},{id:"autumn",emoji:"🍂🍁🌤️😊",label:"秋高气爽天晴朗"},{id:"rainy",emoji:"🌧️",label:"下雨天"}],"autumn","秋高气爽，秋天天气清爽。Crisp autumn!","你理解了 秋高气爽 (autumn)","🍁 秋天美景"));
L.push(choice(118,"nature-island","冰天雪地","看画面理解成语","哪个是冰天雪地？(英文关键词：freezing)","冰天雪地。Freezing cold!",["冰天雪地","freezing"],[{id:"warm",emoji:"☀️🏖️",label:"温暖"},{id:"freezing",emoji:"❄️🏔️🥶",label:"冰天雪地 freezing"},{id:"rainy",emoji:"🌧️",label:"下雨"}],"freezing","冰天雪地，到处是冰和雪。Freezing!","你理解了 冰天雪地 (freezing)","❄️ 冰雪世界"));
L.push(story(119,"nature-island","云淡风轻","看画面理解成语","哪个是云淡风轻","云淡风轻。Light clouds and gentle breeze!",["云淡风轻","gentle"],[{id:"storm",emoji:"⛈️💨",label:"狂风暴雨"},{id:"gentle",emoji:"☁️🍃😊",label:"云淡风轻好天气"},{id:"dark",emoji:"🌑💨",label:"乌云密布"}],"gentle","云淡风轻，天气温和晴朗。Gentle breeze!","你理解了 云淡风轻 (gentle)","🍃 微风拂面"));
L.push(boss(120,"nature-island","自然成语大挑战","四项成语综合","完成四项成语任务","自然成语大闯关！",["风和日丽","雨过天晴","鸟语花香","春暖花开"],[{type:"choice",instruction:"哪个是 风和日丽",prompt:"风和日丽",answer:"fine",options:[{id:"storm",emoji:"⛈️",label:"暴风雨"},{id:"fine",emoji:"☀️🍃",label:"风和日丽 fine"},{id:"cold",emoji:"❄️",label:"天寒地冻"}]},{type:"choice",instruction:"哪个是 雨过天晴",prompt:"雨过天晴",answer:"clear",options:[{id:"rain",emoji:"🌧️",label:"一直下雨"},{id:"clear",emoji:"🌧️➡️☀️",label:"雨过天晴"},{id:"dry",emoji:"🏜️",label:"干旱"}]},{type:"choice",instruction:"哪个是 鸟语花香",prompt:"鸟语花香",answer:"spring",options:[{id:"winter",emoji:"❄️",label:"冬天"},{id:"spring",emoji:"🐦🌸",label:"鸟语花香 spring"},{id:"desert",emoji:"🏜️",label:"沙漠"}]},{type:"choice",instruction:"哪个是 春暖花开",prompt:"春暖花开",answer:"spring2",options:[{id:"snow",emoji:"❄️",label:"下雪"},{id:"spring2",emoji:"🌷🌱",label:"春暖花开"},{id:"autumn",emoji:"🍂",label:"秋天"}]}],"太棒了！自然成语全部通关！","你掌握了自然成语四题","自然成语通关！","🏆 自然成语勋章"));

// ===== 家庭岛 英语 (121-130) =====
L.push(choice(121,"family-island","找到妈妈","听单词选家人","听到口令后，选择正确的","Find mom.",["mom"],[{id:"dad",emoji:"👨",label:"dad"},{id:"mom",emoji:"👩",label:"mom"},{id:"baby",emoji:"👶",label:"baby"}],"mom","Yes! Mom! 👩","你听懂了 mom","👩 妈妈出现了"));
L.push(choice(122,"family-island","找到爸爸","听单词选家人","听到口令后，选择正确的","Find dad.",["dad"],[{id:"mom",emoji:"👩",label:"mom"},{id:"brother",emoji:"👦",label:"brother"},{id:"dad",emoji:"👨",label:"dad"}],"dad","Yes! Dad! 👨","你听懂了 dad","👨 爸爸出现了"));
L.push(choice(123,"family-island","找到姐姐","听单词选家人","听到口令后，选择正确的","Find sister.",["sister"],[{id:"brother",emoji:"👦",label:"brother"},{id:"sister",emoji:"👧",label:"sister"},{id:"baby",emoji:"👶",label:"baby"}],"sister","Yes! Sister! 👧","你听懂了 sister","👧 姐姐出现了"));
L.push(choice(124,"family-island","找到弟弟","听单词选家人","听到口令后，选择正确的","Find brother.",["brother"],[{id:"sister",emoji:"👧",label:"sister"},{id:"dad",emoji:"👨",label:"dad"},{id:"brother",emoji:"👦",label:"brother"}],"brother","Yes! Brother! 👦","你听懂了 brother","👦 弟弟出现了"));
L.push(story(125,"family-island","这是我妈妈","听句子选场景","听句子，选择它描述的画面","This is my mom.",["This is my","mom"],[{id:"dad",emoji:"🧒👨➡️",label:"introducing dad"},{id:"mom",emoji:"🧒👩➡️",label:"introducing mom"},{id:"dog",emoji:"🧒🐶➡️",label:"introducing dog"}],"mom","Yes! This is my mom!","你听懂了 This is my mom","👩‍👧 母女出现"));
L.push(story(126,"family-island","我爱我的家","听句子选场景","听句子，选择它描述的画面","I love my family.",["I love","family"],[{id:"alone",emoji:"🧒🏠😢",label:"alone at home"},{id:"love",emoji:"👨‍👩‍👧‍👦❤️✨",label:"loving family"},{id:"sad",emoji:"👨‍👩‍👧‍👦😢",label:"family arguing"}],"love","Yes! I love my family!","你听懂了 I love my family","❤️ 爱心满溢"));
L.push(wordForge(127,"family-island","拼出 HOME","按顺序拼单词","按听到的顺序点字母","Build home. H. O. M. E. Home.",["home","h","o","m","e"],["E","M","O","H"],"HOME","Yes! H. O. M. E. Home!","你拼出了 HOME","🏠 家拼好了"));
L.push(echo(128,"family-island","跟读：我爱妈妈","听示范并跟读","听完示范，再说同一句话","I love Mom.",["I love","Mom"],["i love mom","love mom","i love"],"Mom loves you too!","你说出了 I love Mom","💕 对妈妈的爱"));
L.push(choice(129,"family-island","找到宝宝","听单词选家人","听到口令后，选择正确的","Find the baby.",["baby"],[{id:"mom",emoji:"👩",label:"mom"},{id:"baby",emoji:"👶",label:"baby"},{id:"dad",emoji:"👨",label:"dad"}],"baby","Yes! Baby! 👶","你听懂了 baby","👶 宝宝出现了"));
L.push(boss(130,"family-island","家庭岛 Boss","四项综合任务","完成四项任务，点亮家庭岛","Let's save Family Island!",["mom","dad","sister","brother"],[{type:"choice",instruction:"选择妈妈",prompt:"Find mom.",answer:"mom",options:[{id:"dad",emoji:"👨",label:"dad"},{id:"mom",emoji:"👩",label:"mom"},{id:"baby",emoji:"👶",label:"baby"}]},{type:"word-forge",instruction:"拼出 DAD",prompt:"Build dad. D. A. D.",answer:"DAD",letters:["A","D","D"]},{type:"choice",instruction:"选择姐姐",prompt:"Find sister.",answer:"sister",options:[{id:"brother",emoji:"👦",label:"brother"},{id:"sister",emoji:"👧",label:"sister"},{id:"baby",emoji:"👶",label:"baby"}]},{type:"echo",instruction:"跟读句子",prompt:"I love my family.",accepted:["i love my family","love my family","my family"]}],"Family Island is saved!","你完成了家庭岛的所有挑战","家庭岛得救了！","✨ 家庭岛完全修复"));

// ===== 家庭岛 成语 (131-140) =====
L.push(story(131,"family-island","尊老爱幼","看画面理解成语","哪个是尊老爱幼","尊老爱幼。Respect the old, love the young!",["尊老爱幼","respect"],[{id:"ignore",emoji:"🧒👴👶❌",label:"不理老人小孩"},{id:"respect",emoji:"🧒👴🤝👶💖",label:"尊重老人爱护小孩"},{id:"bully",emoji:"🧒👴😤👶😰",label:"欺负老人小孩"}],"respect","尊老爱幼，尊重老人爱护小孩。Respect!","你理解了 尊老爱幼 (respect)","🤝 尊老爱幼"));
L.push(story(132,"family-island","兄友弟恭","看画面理解成语","哪个是兄友弟恭","兄友弟恭。Brothers love each other!",["兄友弟恭","brothers"],[{id:"fight",emoji:"👦💢👦",label:"兄弟打架"},{id:"love",emoji:"👦🤝👦😊",label:"兄弟友爱"},{id:"ignore",emoji:"👦📱👦📱",label:"各玩各的"}],"love","兄友弟恭，兄弟友爱。Brothers love each other!","你理解了 兄友弟恭 (brothers)","👦🤝👦 兄弟友爱"));
L.push(story(133,"family-island","相亲相爱","看画面理解成语","哪个是相亲相爱","相亲相爱。Love each other!",["相亲相爱","love"],[{id:"argue",emoji:"👨‍👩‍👧‍👦💢",label:"家人吵架"},{id:"love",emoji:"👨‍👩‍👧‍👦💖✨",label:"家人相亲相爱"},{id:"away",emoji:"👨‍👩‍👧‍👦✈️",label:"家人分离"}],"love","相亲相爱，互相关爱。Love each other!","你理解了 相亲相爱 (love)","💖 爱心之家"));
L.push(story(134,"family-island","血浓于水","看画面理解成语","哪个是血浓于水","血浓于水。Family bonds are strong!",["血浓于水","family bonds"],[{id:"stranger",emoji:"🧒🤝🧒📱",label:"和陌生人更亲"},{id:"bonds",emoji:"👨‍👩‍👧‍👦💪✨",label:"家人感情最深"},{id:"far",emoji:"👨‍👩‍👧‍👦✈️💫",label:"离家很远"}],"bonds","血浓于水，亲情最深厚。Family bonds are strong!","你理解了 血浓于水 (family bonds)","💪 亲情力量"));
L.push(story(135,"family-island","天伦之乐","看画面理解成语","哪个是天伦之乐","天伦之乐。Family happiness!",["天伦之乐","happiness"],[{id:"alone",emoji:"🧒🏠😢",label:"独自在家"},{id:"happiness",emoji:"👨‍👩‍👧‍👦🎉😊",label:"全家幸福快乐"},{id:"work",emoji:"👨💼",label:"爸爸在工作"}],"happiness","天伦之乐，家庭幸福快乐。Family happiness!","你理解了 天伦之乐 (happiness)","🎉 天伦之乐"));
L.push(choice(136,"family-island","骨肉相连","看画面理解成语","哪个是骨肉相连？(英文关键词：close kinship)","骨肉相连。Close kinship!",["骨肉相连","kinship"],[{id:"stranger",emoji:"🧒🧍",label:"陌生人"},{id:"kinship",emoji:"👨‍👩‍👧❤️🔗",label:"骨肉相连 kinship"},{id:"friend",emoji:"🧒🤝🧒",label:"普通朋友"}],"kinship","骨肉相连，亲人关系密切。Close kinship!","你理解了 骨肉相连 (kinship)","🔗 亲情纽带"));
L.push(story(137,"family-island","和睦相处","看画面理解成语","哪个是和睦相处","和睦相处。Live in harmony!",["和睦相处","harmony"],[{id:"argue",emoji:"👨‍👩‍👧‍👦💢😰",label:"天天吵架"},{id:"harmony",emoji:"👨‍👩‍👧‍👦😊✨",label:"和和睦睦过日子"},{id:"cold",emoji:"👨‍👩‍👧‍👦🥶",label:"互不理睬"}],"harmony","和睦相处，和和气气。Live in harmony!","你理解了 和睦相处 (harmony)","🕊️ 和睦之家"));
L.push(choice(138,"family-island","其乐融融","看画面理解成语","哪个是其乐融融？(英文关键词：joyful harmony)","其乐融融。Joyful harmony!",["其乐融融","joyful"],[{id:"tense",emoji:"👨‍👩‍👧‍👦😰",label:"气氛紧张"},{id:"joyful",emoji:"👨‍👩‍👧‍👦😊🎉✨",label:"其乐融融 joyful"},{id:"bored",emoji:"👨‍👩‍👧‍👦🥱",label:"无聊"}],"joyful","其乐融融，快乐融洽。Joyful harmony!","你理解了 其乐融融 (joyful)","✨ 融融快乐"));
L.push(story(139,"family-island","舐犊情深","看画面理解成语","哪个是舐犊情深","舐犊情深。Deep parental love!",["舐犊情深","parental love"],[{id:"strict",emoji:"👩😤👧",label:"很严厉"},{id:"love",emoji:"👩🥰👧💖",label:"父母深深爱孩子"},{id:"ignore",emoji:"👩📱👧",label:"不理孩子"}],"love","舐犊情深，父母深深爱孩子。Deep parental love!","你理解了 舐犊情深 (parental love)","🥰 父母之爱"));
L.push(boss(140,"family-island","家庭成语大挑战","四项成语综合","完成四项成语任务","家庭成语大闯关！",["尊老爱幼","相亲相爱","天伦之乐","和睦相处"],[{type:"choice",instruction:"哪个是 尊老爱幼",prompt:"尊老爱幼",answer:"respect",options:[{id:"ignore",emoji:"👴👶❌",label:"不理"},{id:"respect",emoji:"👴🤝👶",label:"尊老爱幼 respect"},{id:"bully",emoji:"😤",label:"欺负"}]},{type:"choice",instruction:"哪个是 相亲相爱",prompt:"相亲相爱",answer:"love",options:[{id:"argue",emoji:"💢",label:"吵架"},{id:"love",emoji:"👨‍👩‍👧‍👦💖",label:"相亲相爱 love"},{id:"away",emoji:"✈️",label:"分离"}]},{type:"choice",instruction:"哪个是 天伦之乐",prompt:"天伦之乐",answer:"happiness",options:[{id:"alone",emoji:"😢",label:"孤独"},{id:"happiness",emoji:"👨‍👩‍👧‍👦🎉",label:"天伦之乐 happiness"},{id:"work",emoji:"💼",label:"在工作"}]},{type:"choice",instruction:"哪个是 和睦相处",prompt:"和睦相处",answer:"harmony",options:[{id:"argue2",emoji:"💢",label:"吵架"},{id:"harmony",emoji:"😊✨",label:"和睦相处 harmony"},{id:"cold",emoji:"🥶",label:"不理睬"}]}],"太棒了！家庭成语全部通关！","你掌握了家庭成语四题","家庭成语通关！","🏆 家庭成语勋章"));

// ===== 运动岛 英语 (141-150) =====
L.push(choice(141,"sport-island","找到跑","听音选动作","听到口令后，选择正确的动作","Find run.",["run"],[{id:"jump",emoji:"🦘",label:"jump"},{id:"run",emoji:"🏃",label:"run"},{id:"swim",emoji:"🏊",label:"swim"}],"run","Yes! Run! 🏃","你听懂了 run","🏃 跑步出现"));
L.push(choice(142,"sport-island","找到跳","听音选动作","听到口令后，选择正确的动作","Find jump.",["jump"],[{id:"run",emoji:"🏃",label:"run"},{id:"jump",emoji:"🦘",label:"jump"},{id:"dance",emoji:"💃",label:"dance"}],"jump","Yes! Jump! 🦘","你听懂了 jump","🦘 跳跃出现"));
L.push(choice(143,"sport-island","找到游泳","听音选动作","听到口令后，选择正确的动作","Find swim.",["swim"],[{id:"run",emoji:"🏃",label:"run"},{id:"swim",emoji:"🏊",label:"swim"},{id:"fly",emoji:"🦸",label:"fly"}],"swim","Yes! Swim! 🏊","你听懂了 swim","🏊 游泳出现"));
L.push(choice(144,"sport-island","找到唱歌","听音选动作","听到口令后，选择正确的动作","Find sing.",["sing"],[{id:"dance",emoji:"💃",label:"dance"},{id:"sing",emoji:"🎤",label:"sing"},{id:"draw",emoji:"🎨",label:"draw"}],"sing","Yes! Sing! 🎤","你听懂了 sing","🎤 唱歌出现"));
L.push(story(145,"sport-island","我会跑","听句子选场景","听句子，选择它描述的画面","I can run.",["I can","run"],[{id:"cant",emoji:"🧒🚫🏃",label:"can't run"},{id:"can",emoji:"🧒🏃✨",label:"can run"},{id:"want",emoji:"🧒🤔🏃",label:"want to run"}],"can","Yes! I can run!","你听懂了 I can run","🏃 能跑起来"));
L.push(story(146,"sport-island","我们去玩吧","听句子选场景","听句子，选择它描述的画面","Let's play!",["Let's","play"],[{id:"study",emoji:"📚✏️",label:"let's study"},{id:"play",emoji:"⚽🎮✨",label:"let's play"},{id:"eat",emoji:"🍽️",label:"let's eat"}],"play","Yes! Let's play!","你听懂了 Let's play!","⚽ 开玩"));
L.push(wordForge(147,"sport-island","拼出 RUN","按顺序拼单词","按听到的顺序点字母","Build run. R. U. N. Run.",["run","r","u","n"],["N","U","R"],"RUN","Yes! R. U. N. Run!","你拼出了 RUN","🏃 跑拼好了"));
L.push(echo(148,"sport-island","跟读：我会跳","听示范并跟读","听完示范，再说同一句话","I can jump.",["I can","jump"],["i can jump","can jump","jump"],"Great! You can jump!","你说出了 I can jump","🦘 跳起来"));
L.push(choice(149,"sport-island","找到跳舞","听音选动作","听到口令后，选择正确的动作","Find dance.",["dance"],[{id:"sing",emoji:"🎤",label:"sing"},{id:"dance",emoji:"💃",label:"dance"},{id:"draw",emoji:"🎨",label:"draw"}],"dance","Yes! Dance! 💃","你听懂了 dance","💃 跳舞出现"));
L.push(boss(150,"sport-island","运动岛 Boss","四项综合任务","完成四项任务，点亮运动岛","Let's save Sport Island!",["run","jump","swim","sing"],[{type:"choice",instruction:"选择跑",prompt:"Find run.",answer:"run",options:[{id:"jump",emoji:"🦘",label:"jump"},{id:"run",emoji:"🏃",label:"run"},{id:"swim",emoji:"🏊",label:"swim"}]},{type:"word-forge",instruction:"拼出 JUMP",prompt:"Build jump. J. U. M. P.",answer:"JUMP",letters:["P","M","U","J"]},{type:"choice",instruction:"选择游泳",prompt:"Find swim.",answer:"swim",options:[{id:"run",emoji:"🏃",label:"run"},{id:"swim",emoji:"🏊",label:"swim"},{id:"fly",emoji:"🦸",label:"fly"}]},{type:"echo",instruction:"跟读句子",prompt:"I can jump.",accepted:["i can jump","can jump","jump"]}],"Sport Island is saved!","你完成了运动岛的所有挑战","运动岛得救了！","✨ 运动岛完全修复"));

// ===== 运动岛 成语 (151-160) =====
L.push(story(151,"sport-island","奋勇争先","看画面理解成语","哪个是奋勇争先","奋勇争先。Strive to be first!",["奋勇争先","strive"],[{id:"lazy",emoji:"🧒🛌",label:"懒洋洋"},{id:"strive",emoji:"🧒🏃💨✨",label:"努力冲在前面"},{id:"slow",emoji:"🧒🚶",label:"慢慢走"}],"strive","奋勇争先，努力争第一。Strive to be first!","你理解了 奋勇争先 (strive)","🥇 冲刺星"));
L.push(story(152,"sport-island","坚持不懈","看画面理解成语","哪个是坚持不懈","坚持不懈。Never give up!",["坚持不懈","persist"],[{id:"quit",emoji:"🧒🛑😢",label:"中途放弃"},{id:"persist",emoji:"🧒💪✨➡️✅",label:"一直坚持不放弃"},{id:"try",emoji:"🧒🔄",label:"试试看"}],"persist","坚持不懈，一直不放弃。Never give up!","你理解了 坚持不懈 (persist)","💪 坚持勋章"));
L.push(story(153,"sport-island","再接再厉","看画面理解成语","哪个是再接再厉","再接再厉。Keep improving!",["再接再厉","improve"],[{id:"rest",emoji:"🧒🏆😴",label:"赢了就休息"},{id:"improve",emoji:"🧒🏆➡️💪➡️🏆✨",label:"赢了继续努力"},{id:"sad",emoji:"🧒😢",label:"输了就哭"}],"improve","再接再厉，继续努力更好。Keep improving!","你理解了 再接再厉 (improve)","📈 进步箭头"));
L.push(story(154,"sport-island","百折不挠","看画面理解成语","哪个是百折不挠","百折不挠。Unyielding!",["百折不挠","unyielding"],[{id:"giveup",emoji:"🧒💥😢",label:"失败就放弃"},{id:"unyielding",emoji:"🧒💥➡️💪➡️✨",label:"失败很多次仍不屈服"},{id:"lucky",emoji:"🧒🍀",label:"靠运气"}],"unyielding","百折不挠，再难也不屈服。Unyielding!","你理解了 百折不挠 (unyielding)","🔥 不屈之火"));
L.push(choice(155,"sport-island","勇往直前","看画面理解成语","哪个是勇往直前？(英文关键词：forge ahead)","勇往直前。Forge ahead!",["勇往直前","forge ahead"],[{id:"back",emoji:"🧒⬅️😰",label:"退缩"},{id:"forge",emoji:"🧒➡️💪✨",label:"勇往直前 forge ahead"},{id:"wait",emoji:"🧒⏸️",label:"等一等"}],"forge","勇往直前，勇敢向前。Forge ahead!","你理解了 勇往直前 (forge ahead)","⚔️ 勇敢之剑"));
L.push(story(156,"sport-island","全力以赴","看画面理解成语","哪个是全力以赴","全力以赴。Give it your all!",["全力以赴","all out"],[{id:"half",emoji:"🧒50%💪",label:"只使了一半力气"},{id:"allout",emoji:"🧒100%💪🔥✨",label:"使出全部力量"},{id:"skip",emoji:"🧒🙅",label:"不参加"}],"allout","全力以赴，拿出全部力量。Give it your all!","你理解了 全力以赴 (all out)","🔥 全力之火"));
L.push(choice(157,"sport-island","锲而不舍","看画面理解成语","哪个是锲而不舍？(英文关键词：persevere)","锲而不舍。Persevere!",["锲而不舍","persevere"],[{id:"quit",emoji:"🧒🛑",label:"放弃"},{id:"persevere",emoji:"🧒🔨💎✨",label:"锲而不舍 persevere"},{id:"try",emoji:"🧒🤔",label:"试试看"}],"persevere","锲而不舍，不停地刻。Persevere!","你理解了 锲而不舍 (persevere)","💎 恒心钻石"));
L.push(story(158,"sport-island","持之以恒","看画面理解成语","哪个是持之以恒","持之以恒。Keep it up consistently!",["持之以恒","consistent"],[{id:"offon",emoji:"🧒📅⏸️📅⏸️",label:"三天打鱼两天晒网"},{id:"consistent",emoji:"🧒📅✅📅✅📅✨",label:"每天坚持"},{id:"start",emoji:"🧒📅",label:"刚开始"}],"consistent","持之以恒，长久坚持。Keep it up!","你理解了 持之以恒 (consistent)","📅 日历之星"));
L.push(choice(159,"sport-island","精益求精","看画面理解成语","哪个是精益求精？(英文关键词：perfect)","精益求精。Always perfecting!",["精益求精","perfect"],[{id:"ok",emoji:"🧒👍",label:"差不多就行"},{id:"perfect",emoji:"🧒✨💎✨",label:"精益求精 perfect"},{id:"worse",emoji:"🧒📉",label:"越做越差"}],"perfect","精益求精，追求更好。Always perfecting!","你理解了 精益求精 (perfect)","💎 完美之钻"));
L.push(boss(160,"sport-island","运动成语大挑战","四项成语综合","完成四项成语任务","运动成语大闯关！",["奋勇争先","坚持不懈","百折不挠","勇往直前"],[{type:"choice",instruction:"哪个是 奋勇争先",prompt:"奋勇争先",answer:"strive",options:[{id:"lazy",emoji:"🛌",label:"懒洋洋"},{id:"strive",emoji:"🏃💨✨",label:"奋勇争先 strive"},{id:"slow",emoji:"🚶",label:"慢慢走"}]},{type:"choice",instruction:"哪个是 坚持不懈",prompt:"坚持不懈",answer:"persist",options:[{id:"quit",emoji:"🛑😢",label:"放弃"},{id:"persist",emoji:"💪✨",label:"坚持不懈 persist"},{id:"try",emoji:"🔄",label:"试试看"}]},{type:"choice",instruction:"哪个是 百折不挠",prompt:"百折不挠",answer:"unyielding",options:[{id:"giveup",emoji:"💥😢",label:"放弃"},{id:"unyielding",emoji:"💥➡️💪",label:"百折不挠"},{id:"lucky",emoji:"🍀",label:"靠运气"}]},{type:"choice",instruction:"哪个是 勇往直前",prompt:"勇往直前",answer:"forge",options:[{id:"back",emoji:"⬅️😰",label:"退缩"},{id:"forge",emoji:"➡️💪",label:"勇往直前 forge"},{id:"wait",emoji:"⏸️",label:"等一等"}]}],"太棒了！运动成语全部通关！","你掌握了运动成语四题","运动成语通关！","🏆 运动成语勋章"));

// ===== 身体岛 英语 (161-170) =====
L.push(choice(161,"body-island","找到头","听单词选身体","听到口令后，选择正确的","Find the head.",["head"],[{id:"hand",emoji:"✋",label:"hand"},{id:"head",emoji:"🧑",label:"head"},{id:"foot",emoji:"🦶",label:"foot"}],"head","Yes! Head! 🧑","你听懂了 head","🧑 头出现了"));
L.push(choice(162,"body-island","找到眼睛","听单词选身体","听到口令后，选择正确的","Find the eye.",["eye"],[{id:"ear",emoji:"👂",label:"ear"},{id:"eye",emoji:"👁️",label:"eye"},{id:"nose",emoji:"👃",label:"nose"}],"eye","Yes! Eye! 👁️","你听懂了 eye","👁️ 眼睛出现了"));
L.push(choice(163,"body-island","找到耳朵","听单词选身体","听到口令后，选择正确的","Find the ear.",["ear"],[{id:"eye",emoji:"👁️",label:"eye"},{id:"mouth",emoji:"👄",label:"mouth"},{id:"ear",emoji:"👂",label:"ear"}],"ear","Yes! Ear! 👂","你听懂了 ear","👂 耳朵出现了"));
L.push(choice(164,"body-island","找到鼻子","听单词选身体","听到口令后，选择正确的","Find the nose.",["nose"],[{id:"eye",emoji:"👁️",label:"eye"},{id:"nose",emoji:"👃",label:"nose"},{id:"mouth",emoji:"👄",label:"mouth"}],"nose","Yes! Nose! 👃","你听懂了 nose","👃 鼻子出现了"));
L.push(story(165,"body-island","摸摸你的头","听句子选场景","听句子，选择它描述的画面","Touch your head.",["Touch your","head"],[{id:"nose",emoji:"✋👃",label:"touch nose"},{id:"head",emoji:"✋🧑",label:"touch head"},{id:"ear",emoji:"✋👂",label:"touch ear"}],"head","Yes! Touch your head!","你听懂了 Touch your head","✋ 摸摸头"));
L.push(story(166,"body-island","张开嘴巴","听句子选场景","听句子，选择它描述的画面","Open your mouth.",["Open your","mouth"],[{id:"close",emoji:"🤐",label:"mouth closed"},{id:"open",emoji:"😮✨",label:"mouth open"},{id:"nose",emoji:"👃",label:"touch nose"}],"open","Yes! Open your mouth!","你听懂了 Open your mouth","😮 张嘴"));
L.push(wordForge(167,"body-island","拼出 HAND","按顺序拼单词","按听到的顺序点字母","Build hand. H. A. N. D. Hand.",["hand","h","a","n","d"],["N","D","A","H"],"HAND","Yes! H. A. N. D. Hand!","你拼出了 HAND","✋ 手拼好了"));
L.push(echo(168,"body-island","跟读：摸摸你的鼻子","听示范并跟读","听完示范，再说同一句话","Touch your nose.",["Touch your","nose"],["touch your nose","your nose","touch nose"],"Good job!","你说出了 Touch your nose","👃 摸鼻子"));
L.push(choice(169,"body-island","找到手","听单词选身体","听到口令后，选择正确的","Find the hand.",["hand"],[{id:"foot",emoji:"🦶",label:"foot"},{id:"hand",emoji:"✋",label:"hand"},{id:"head",emoji:"🧑",label:"head"}],"hand","Yes! Hand! ✋","你听懂了 hand","✋ 手出现了"));
L.push(boss(170,"body-island","身体岛 Boss","四项综合任务","完成四项任务，点亮身体岛","Let's save Body Island!",["head","eye","nose","hand"],[{type:"choice",instruction:"选择头",prompt:"Find the head.",answer:"head",options:[{id:"hand",emoji:"✋",label:"hand"},{id:"head",emoji:"🧑",label:"head"},{id:"foot",emoji:"🦶",label:"foot"}]},{type:"word-forge",instruction:"拼出 EYE",prompt:"Build eye. E. Y. E.",answer:"EYE",letters:["Y","E","E"]},{type:"choice",instruction:"选择鼻子",prompt:"Find the nose.",answer:"nose",options:[{id:"eye",emoji:"👁️",label:"eye"},{id:"nose",emoji:"👃",label:"nose"},{id:"mouth",emoji:"👄",label:"mouth"}]},{type:"echo",instruction:"跟读句子",prompt:"Touch your head.",accepted:["touch your head","your head","touch head"]}],"Body Island is saved!","你完成了身体岛的所有挑战","身体岛得救了！","✨ 身体岛完全修复"));

// ===== 身体岛 成语 (171-180) =====
L.push(story(171,"body-island","眼明手快","看画面理解成语","哪个是眼明手快","眼明手快。Quick eyes and hands!",["眼明手快","quick"],[{id:"slow",emoji:"🧒👀🦥✋",label:"反应很慢"},{id:"quick",emoji:"🧒👀⚡✋✨",label:"眼明手快反应快"},{id:"careless",emoji:"🧒😵💥",label:"粗心大意"}],"quick","眼明手快，眼力好动作快。Quick!","你理解了 眼明手快 (quick)","⚡ 灵敏星"));
L.push(story(172,"body-island","耳聪目明","看画面理解成语","哪个是耳聪目明","耳聪目明。Sharp ears and eyes!",["耳聪目明","sharp"],[{id:"deaf",emoji:"🧒👂🔇👁️🔇",label:"听不清看不清"},{id:"sharp",emoji:"🧒👂✨👁️✨",label:"耳聪目明很灵敏"},{id:"young",emoji:"🧒😊",label:"只是年轻"}],"sharp","耳聪目明，听觉视觉都好。Sharp!","你理解了 耳聪目明 (sharp)","👂👁️ 灵敏之耳目"));
L.push(choice(173,"body-island","口若悬河","看画面理解成语","哪个是口若悬河？(英文关键词：eloquent)","口若悬河。Eloquent!",["口若悬河","eloquent"],[{id:"quiet",emoji:"🧒🤐",label:"沉默寡言 quiet"},{id:"eloquent",emoji:"🧒🗣️🌊✨",label:"口若悬河 eloquent"},{id:"mumble",emoji:"🧒😬",label:"吞吞吐吐"}],"eloquent","口若悬河，说话滔滔不绝。Eloquent!","你理解了 口若悬河 (eloquent)","🌊 滔滔不绝"));
L.push(story(174,"body-island","手舞足蹈","看画面理解成语","哪个是手舞足蹈","手舞足蹈。Jump for joy!",["手舞足蹈","jump for joy"],[{id:"sad",emoji:"😢",label:"难过"},{id:"dance",emoji:"💃🕺🎶",label:"开心得又跳又舞"},{id:"sit",emoji:"🪑",label:"坐着"}],"dance","手舞足蹈，高兴得又跳又舞。Jump for joy!","你理解了 手舞足蹈 (jump for joy)","💃 跳舞小人"));
L.push(choice(175,"body-island","足智多谋","看画面理解成语","哪个是足智多谋？(英文关键词：resourceful)","足智多谋。Resourceful!",["足智多谋","resourceful"],[{id:"simple",emoji:"🧒🤷",label:"头脑简单"},{id:"resourceful",emoji:"🧒💡🧠✨",label:"足智多谋 resourceful"},{id:"copy",emoji:"🧒📋",label:"抄别人"}],"resourceful","足智多谋，智慧多计谋多。Resourceful!","你理解了 足智多谋 (resourceful)","💡 智慧星"));
L.push(story(176,"body-island","眉开眼笑","看画面理解成语","哪个是眉开眼笑","眉开眼笑。Smile happily!",["眉开眼笑","smile"],[{id:"frown",emoji:"😟",label:"皱眉"},{id:"smile",emoji:"😄😊",label:"开心微笑"},{id:"cry",emoji:"😭",label:"哭泣"}],"smile","眉开眼笑，眉毛舒展眼睛含笑。Smile happily!","你理解了 眉开眼笑 (smile)","😊 微笑表情"));
L.push(story(177,"body-island","昂首挺胸","看画面理解成语","哪个是昂首挺胸","昂首挺胸。Stand tall and proud!",["昂首挺胸","proud"],[{id:"bow",emoji:"🧒😔👇",label:"低着头驼背"},{id:"proud",emoji:"🧒😊💪✨",label:"昂首挺胸很自信"},{id:"sit",emoji:"🧒🪑",label:"坐着"}],"proud","昂首挺胸，自信挺拔。Stand tall!","你理解了 昂首挺胸 (proud)","💪 自信之星"));
L.push(story(178,"body-island","一目十行","看画面理解成语","哪个是一目十行","一目十行。Read very fast!",["一目十行","fast reader"],[{id:"slow",emoji:"🧒📖🐌",label:"一行一行慢慢读"},{id:"fast",emoji:"🧒📖⚡✨",label:"一目十行读得快"},{id:"skip",emoji:"🧒📖❌",label:"不读书"}],"fast","一目十行，看书非常快。Read very fast!","你理解了 一目十行 (fast reader)","📖 速读之星"));
L.push(choice(179,"body-island","七嘴八舌","看画面理解成语","哪个是七嘴八舌？(英文关键词：chatter)","七嘴八舌。Everyone chatters!",["七嘴八舌","chatter"],[{id:"quiet",emoji:"🤐🤐",label:"安安静静"},{id:"chatter",emoji:"🗣️🗣️🗣️💬✨",label:"七嘴八舌 chatter"},{id:"one",emoji:"🗣️",label:"只有一个人说"}],"chatter","七嘴八舌，大家争着说话。Chatter!","你理解了 七嘴八舌 (chatter)","💬 热闹讨论"));
L.push(boss(180,"body-island","身体成语大挑战","四项成语综合","完成四项成语任务","身体成语大闯关！",["眼明手快","耳聪目明","手舞足蹈","眉开眼笑"],[{type:"choice",instruction:"哪个是 眼明手快",prompt:"眼明手快",answer:"quick",options:[{id:"slow",emoji:"🦥",label:"慢"},{id:"quick",emoji:"⚡",label:"眼明手快 quick"},{id:"careless",emoji:"💥",label:"粗心"}]},{type:"choice",instruction:"哪个是 耳聪目明",prompt:"耳聪目明",answer:"sharp",options:[{id:"deaf",emoji:"🔇",label:"听不清"},{id:"sharp",emoji:"👂✨👁️",label:"耳聪目明 sharp"},{id:"young",emoji:"😊",label:"年轻"}]},{type:"choice",instruction:"哪个是 手舞足蹈",prompt:"手舞足蹈",answer:"dance",options:[{id:"sad",emoji:"😢",label:"难过"},{id:"dance",emoji:"💃",label:"手舞足蹈"},{id:"sit",emoji:"🪑",label:"坐着"}]},{type:"choice",instruction:"哪个是 眉开眼笑",prompt:"眉开眼笑",answer:"smile",options:[{id:"frown",emoji:"😟",label:"皱眉"},{id:"smile",emoji:"😄",label:"眉开眼笑 smile"},{id:"cry",emoji:"😭",label:"哭泣"}]}],"太棒了！身体成语全部通关！","你掌握了身体成语四题","身体成语通关！","🏆 身体成语勋章"));

// ===== 彩虹岛 英语 (181-190) - 综合复习 =====
L.push(choice(181,"rainbow-island","复习：小猫","综合复习","听到口令后，选择正确的","Find the cat.",["cat"],[{id:"dog",emoji:"🐶",label:"dog"},{id:"cat",emoji:"🐱",label:"cat"},{id:"bird",emoji:"🐦",label:"bird"}],"cat","Yes! Cat! 🐱","你复习了 cat","🐱 复习成功"));
L.push(choice(182,"rainbow-island","复习：开心","综合复习","听到口令后，选择正确的","Find happy.",["happy"],[{id:"sad",emoji:"😢",label:"sad"},{id:"happy",emoji:"😄",label:"happy"},{id:"angry",emoji:"😡",label:"angry"}],"happy","Yes! Happy! 😄","你复习了 happy","😄 情感复习"));
L.push(story(183,"rainbow-island","复习：我想要蛋糕","综合复习","听句子，选择它描述的画面","I would like some cake.",["I would like","cake"],[{id:"bread",emoji:"🍞🙋",label:"want bread"},{id:"cake",emoji:"🍰🙋",label:"want cake"},{id:"rice",emoji:"🍚🙋",label:"want rice"}],"cake","Yes! I would like some cake!","你复习了 I would like some cake","🍰 美食复习"));
L.push(story(184,"rainbow-island","复习：这是我的妈妈","综合复习","听句子，选择它描述的画面","This is my mom.",["This is my","mom"],[{id:"dad",emoji:"🧒👨",label:"introducing dad"},{id:"mom",emoji:"🧒👩",label:"introducing mom"},{id:"sister",emoji:"🧒👧",label:"introducing sister"}],"mom","Yes! This is my mom!","你复习了 This is my mom","👩 家庭复习"));
L.push(choice(185,"rainbow-island","复习：太阳","综合复习","听到口令后，选择正确的","Find the sun.",["sun"],[{id:"moon",emoji:"🌙",label:"moon"},{id:"sun",emoji:"☀️",label:"sun"},{id:"star",emoji:"⭐",label:"star"}],"sun","Yes! Sun! ☀️","你复习了 sun","☀️ 自然复习"));
L.push(wordForge(186,"rainbow-island","拼出 RUN","综合复习","按听到的顺序点字母","Build run. R. U. N. Run.",["run","r","u","n"],["N","U","R"],"RUN","Yes! R. U. N. Run!","你复习了 run","🏃 运动复习"));
L.push(echo(187,"rainbow-island","跟读：摸你的头","综合复习","听完示范，再说同一句话","Touch your head.",["Touch your","head"],["touch your head","your head","touch head"],"Good job!","你复习了 Touch your head","✋ 身体复习"));
L.push(choice(188,"rainbow-island","复习：书本","综合复习","听到口令后，选择正确的","Find the book.",["book"],[{id:"pencil",emoji:"✏️",label:"pencil"},{id:"book",emoji:"📘",label:"book"},{id:"bag",emoji:"🎒",label:"bag"}],"book","Yes! Book! 📘","你复习了 book","📘 校园复习"));
L.push(story(189,"rainbow-island","复习：穿上鞋子","综合复习","听句子，选择它描述的画面","Put on your shoes.",["put on","shoes"],[{id:"coat",emoji:"🧥✅",label:"put on coat"},{id:"shoes",emoji:"👟✅",label:"put on shoes"},{id:"hat",emoji:"🧢✅",label:"put on hat"}],"shoes","Yes! Put on your shoes!","你复习了 Put on your shoes","👟 生活复习"));
L.push(boss(190,"rainbow-island","彩虹岛 Boss","四项综合任务","完成四项任务，点亮彩虹岛","Let's save Rainbow Island!",["cat","happy","book","run"],[{type:"choice",instruction:"选择小猫",prompt:"Find the cat.",answer:"cat",options:[{id:"dog",emoji:"🐶",label:"dog"},{id:"cat",emoji:"🐱",label:"cat"},{id:"bird",emoji:"🐦",label:"bird"}]},{type:"word-forge",instruction:"拼出 BOOK",prompt:"Build book. B. O. O. K.",answer:"BOOK",letters:["O","K","B","O"]},{type:"choice",instruction:"选择开心",prompt:"Find happy.",answer:"happy",options:[{id:"sad",emoji:"😢",label:"sad"},{id:"happy",emoji:"😄",label:"happy"},{id:"angry",emoji:"😡",label:"angry"}]},{type:"echo",instruction:"跟读句子",prompt:"I can run.",accepted:["i can run","can run","run"]}],"Rainbow Island is saved!","你完成了彩虹岛的所有挑战","彩虹岛得救了！","✨ 彩虹岛完全修复"));

// ===== 彩虹岛 成语 (191-200) - 综合成语 =====
L.push(story(191,"rainbow-island","集思广益","看画面理解成语","哪个是集思广益","集思广益。Pool wisdom!",["集思广益","pool wisdom"],[{id:"alone",emoji:"🧒🤔",label:"一个人想"},{id:"pool",emoji:"👥💡✨",label:"大家一起想办法"},{id:"argue",emoji:"👥💢",label:"大家吵架"}],"pool","集思广益，集中大家的智慧。Pool wisdom!","你理解了 集思广益 (pool wisdom)","💡 智慧集合"));
L.push(story(192,"rainbow-island","众志成城","看画面理解成语","哪个是众志成城","众志成城。United we stand!",["众志成城","united"],[{id:"divide",emoji:"👥💥",label:"分裂不团结"},{id:"united",emoji:"👥🤝🏰✨",label:"团结起来力量大"},{id:"alone2",emoji:"🧒😰",label:"一个人孤军奋战"}],"united","众志成城，团结一致力量大。United we stand!","你理解了 众志成城 (united)","🏰 团结城堡"));
L.push(story(193,"rainbow-island","同心协力","看画面理解成语","哪个是同心协力","同心协力。Work together!",["同心协力","together"],[{id:"fight",emoji:"👥💢",label:"互相打架"},{id:"together",emoji:"👥🤝💪✨",label:"齐心协力一起干"},{id:"ignore",emoji:"🧒🙈",label:"各管各的"}],"together","同心协力，齐心合力。Work together!","你理解了 同心协力 (together)","🤝 齐心协力"));
L.push(story(194,"rainbow-island","取长补短","看画面理解成语","哪个是取长补短","取长补短。Learn from each other!",["取长补短","complement"],[{id:"copy",emoji:"🧒📋",label:"完全抄别人"},{id:"complement",emoji:"🧒🤝↔️✨",label:"互相学习长处补短处"},{id:"mock",emoji:"🧒😏",label:"嘲笑别人短处"}],"complement","取长补短，学习长处弥补短处。Learn from each other!","你理解了 取长补短 (complement)","↔️ 互补"));
L.push(story(195,"rainbow-island","见义勇为","看画面理解成语","哪个是见义勇为","见义勇为。Act bravely for justice!",["见义勇为","brave"],[{id:"watch",emoji:"🧒👀",label:"看着不管"},{id:"brave",emoji:"🧒💪❤️✨",label:"勇敢地站出来"},{id:"run",emoji:"🧒🏃💨",label:"赶紧跑开"}],"brave","见义勇为，看到正义的事勇敢去做。Act bravely!","你理解了 见义勇为 (brave)","❤️ 勇敢之心"));
L.push(choice(196,"rainbow-island","实事求是","看画面理解成语","哪个是实事求是？(英文关键词：practical)","实事求是。Be practical!",["实事求是","practical"],[{id:"exaggerate",emoji:"🧒📈😄",label:"夸大其词"},{id:"practical",emoji:"🧒📊✅✨",label:"实事求是 practical"},{id:"lie",emoji:"🧒🤥",label:"说假话"}],"practical","实事求是，从实际出发。Be practical!","你理解了 实事求是 (practical)","📊 求实"));
L.push(story(197,"rainbow-island","脚踏实地","看画面理解成语","哪个是脚踏实地","脚踏实地。Down to earth!",["脚踏实地","down to earth"],[{id:"dream",emoji:"🧒☁️💭",label:"光想不做"},{id:"earth",emoji:"🧒🦶🌍💪✨",label:"脚踏实地认真干"},{id:"rush",emoji:"🧒💨",label:"急功近利"}],"earth","脚踏实地，认真踏实地干。Down to earth!","你理解了 脚踏实地 (down to earth)","🌍 踏实"));
L.push(choice(198,"rainbow-island","有始有终","看画面理解成语","哪个是有始有终？(英文关键词：finish what you start)","有始有终。Finish what you start!",["有始有终","finish"],[{id:"quit",emoji:"🧒🛑",label:"半途而废"},{id:"finish",emoji:"🧒✅➡️✅✨",label:"有始有终 finish"},{id:"start",emoji:"🧒🚀",label:"只有开始"}],"finish","有始有终，做事有开头也有结尾。Finish what you start!","你理解了 有始有终 (finish)","✅ 有始有终"));
L.push(story(199,"rainbow-island","大公无私","看画面理解成语","哪个是大公无私","大公无私。Selfless!",["大公无私","selfless"],[{id:"selfish",emoji:"🧒💰😌",label:"只顾自己"},{id:"selfless",emoji:"🧒🤝❤️✨",label:"大公无私为别人"},{id:"fair",emoji:"🧒⚖️",label:"只是公平"}],"selfless","大公无私，没有私心。Selfless!","你理解了 大公无私 (selfless)","❤️ 无私之心"));
L.push(boss(200,"rainbow-island","成语大闯关","四项成语综合","完成四项成语任务","成语大闯关！最终挑战！",["集思广益","众志成城","见义勇为","脚踏实地"],[{type:"choice",instruction:"哪个是 集思广益",prompt:"集思广益",answer:"pool",options:[{id:"alone",emoji:"🤔",label:"一个人想"},{id:"pool",emoji:"👥💡",label:"集思广益 pool wisdom"},{id:"argue",emoji:"💢",label:"吵架"}]},{type:"choice",instruction:"哪个是 众志成城",prompt:"众志成城",answer:"united",options:[{id:"divide",emoji:"💥",label:"分裂"},{id:"united",emoji:"🤝🏰",label:"众志成城 united"},{id:"alone2",emoji:"😰",label:"孤军奋战"}]},{type:"choice",instruction:"哪个是 见义勇为",prompt:"见义勇为",answer:"brave",options:[{id:"watch",emoji:"👀",label:"看着不管"},{id:"brave",emoji:"💪❤️",label:"见义勇为 brave"},{id:"run2",emoji:"🏃💨",label:"跑开"}]},{type:"choice",instruction:"哪个是 脚踏实地",prompt:"脚踏实地",answer:"earth",options:[{id:"dream",emoji:"☁️💭",label:"光想不做"},{id:"earth",emoji:"🦶🌍",label:"脚踏实地"},{id:"rush",emoji:"💨",label:"急功近利"}]}],"太棒了！全部成语通关！","你掌握了最终成语四题","成语大闯关通关！","🏆 最终成语勋章"));

// Generate output
const output = `(function attachLevels(root) {
  "use strict";

  root.GAME_WORLDS = ${JSON.stringify(GAME_WORLDS, null, 2)};

  root.GAME_LEVELS = ${JSON.stringify(L, null, 2)};

})(typeof globalThis !== "undefined" ? globalThis : this);
`;

fs.writeFileSync(path.join(__dirname, 'levels.js'), output, 'utf8');
console.log(`Generated levels.js with ${L.length} levels`);
