(function attachLevels(root) {
  "use strict";

  root.GAME_WORLDS = [
    {
      id: "animal-harbor",
      title: "动物港",
      englishTitle: "Animal Harbor",
      scene: ["🐱", "⛵", "🗼"],
      description: "听懂动物、颜色和简单动作，修复声音灯塔。",
    },
    {
      id: "school-city",
      title: "小学城",
      englishTitle: "School City",
      scene: ["🏫", "🎒", "✏️"],
      description: "练习见老师、进教室、求助、找物品和交朋友。",
    },
    {
      id: "life-town",
      title: "生活小镇",
      englishTitle: "Life Town",
      scene: ["🏡", "🥛", "🚦"],
      description: "把英语带进早餐、穿衣、过马路、午餐和玩耍。",
    },
    {
      id: "idiom-island",
      title: "成语彩蛋岛",
      englishTitle: "Idiom Island",
      scene: ["📜", "🐉", "✨"],
      description: "用画面理解四个适龄成语；这是独立中文彩蛋课程。",
    },
  ];

  root.GAME_LEVELS = [
    {
      id: "level-1",
      number: 1,
      worldId: "animal-harbor",
      title: "找到小猫",
      skill: "听音选动物",
      type: "choice",
      instruction: "听到口令后，点小猫",
      prompt: "Find the cat.",
      audio: "audio/level-1-find-cat.mp3",
      words: ["cat"],
      options: [
        { id: "dog", emoji: "🐶", label: "dog" },
        { id: "cat", emoji: "🐱", label: "cat" },
        { id: "bird", emoji: "🐦", label: "bird" },
      ],
      answer: "cat",
      promptTarget: "cat",
      success: "Yes! Cat.",
      completion: "你听懂了 “cat”",
      sceneReward: "🐱 小猫回到了动物港",
    },
    {
      id: "level-2",
      number: 2,
      worldId: "animal-harbor",
      title: "红色钥匙",
      skill: "听颜色指令",
      type: "choice",
      instruction: "听到口令后，选择正确颜色的钥匙",
      prompt: "Give me the red key.",
      audio: "audio/level-2-red-key.mp3",
      words: ["red", "blue", "key"],
      options: [
        { id: "blue", emoji: "🔑", label: "blue", color: "#5aa9e6" },
        { id: "red", emoji: "🔑", label: "red", color: "#ff6b6b" },
      ],
      answer: "red",
      promptTarget: "red",
      success: "Yes! Red key.",
      completion: "你听懂了 “red key”",
      sceneReward: "🏮 红灯笼亮起来了",
    },
    {
      id: "level-3",
      number: 3,
      worldId: "animal-harbor",
      title: "小狗上船",
      skill: "听指令做动作",
      type: "action",
      instruction: "先选小狗，再把它送上船",
      prompt: "Put the dog on the boat.",
      audio: "audio/level-3-dog-boat.mp3",
      words: ["dog", "boat"],
      items: [
        { id: "bird", emoji: "🐦", label: "bird", audio: "audio/word-bird.mp3" },
        { id: "dog", emoji: "🐶", label: "dog", audio: "audio/word-dog.mp3" },
        { id: "fish", emoji: "🐟", label: "fish", audio: "audio/word-fish.mp3" },
      ],
      answer: "dog",
      success: "Yes! The dog is on the boat.",
      completion: "你完成了 “dog on the boat”",
      sceneReward: "⛵ 动物小船修好了",
    },
    {
      id: "level-4",
      number: 4,
      worldId: "animal-harbor",
      title: "声音洞穴",
      skill: "听首音选字母",
      type: "sound-match",
      instruction: "听 sun 的第一个音，选择字母",
      prompt: "Sun starts with S. Find S.",
      audio: "audio/level-4-sound-s.mp3",
      words: ["sun", "s"],
      options: [
        { id: "m", emoji: "Ⓜ️", label: "M" },
        { id: "s", emoji: "☀️", label: "S" },
        { id: "a", emoji: "🍎", label: "A" },
      ],
      answer: "s",
      promptTarget: "S",
      success: "Yes! S, sun.",
      completion: "你找到了 sun 的首音 /s/",
      sceneReward: "☀️ 阳光照进了洞穴",
    },
    {
      id: "level-5",
      number: 5,
      worldId: "animal-harbor",
      title: "锻造 CAT",
      skill: "按顺序拼单词",
      type: "word-forge",
      instruction: "按听到的顺序点字母",
      prompt: "Build cat. C. A. T. Cat.",
      audio: "audio/level-5-build-cat.mp3",
      words: ["cat", "c", "a", "t"],
      letters: ["T", "C", "A"],
      answer: "CAT",
      success: "Yes! C. A. T. Cat.",
      completion: "你拼出了 CAT",
      sceneReward: "🔤 声音锻炉重新工作了",
    },
    {
      id: "level-6",
      number: 6,
      worldId: "animal-harbor",
      title: "谁在水里",
      skill: "听句子选场景",
      type: "story",
      instruction: "听句子，选择它描述的画面",
      prompt: "I see a fish.",
      audio: "audio/level-6-see-fish.mp3",
      words: ["fish", "I see a"],
      options: [
        { id: "bird", emoji: "🐦🌳", label: "a bird in a tree" },
        { id: "fish", emoji: "🐟🌊", label: "a fish in the water" },
        { id: "cat", emoji: "🐱📦", label: "a cat in a box" },
      ],
      answer: "fish",
      promptTarget: "fish",
      success: "Yes! I see a fish.",
      completion: "你听懂了 “I see a fish”",
      sceneReward: "🐟 小鱼找到了回家的水道",
    },
    {
      id: "level-7",
      number: 7,
      worldId: "animal-harbor",
      title: "回声桥",
      skill: "听示范并跟读",
      type: "echo",
      instruction: "听完示范，再说同一句话",
      prompt: "I see a cat.",
      audio: "audio/level-7-see-cat.mp3",
      words: ["cat", "I see a"],
      accepted: ["i see a cat", "see a cat", "cat"],
      success: "Yes! I see a cat.",
      completion: "你说出了 “I see a cat”",
      sceneReward: "🌉 回声桥升起来了",
    },
    {
      id: "level-8",
      number: 8,
      worldId: "animal-harbor",
      title: "灯塔 Boss",
      skill: "四项综合任务",
      type: "boss",
      instruction: "完成四项任务，点亮灯塔",
      prompt: "Let's save Animal Harbor!",
      words: ["red", "dog", "cat", "open the door"],
      steps: [
        {
          type: "choice",
          instruction: "选择红色钥匙",
          prompt: "Find the red key.",
          audio: "audio/boss-1-red-key.mp3",
          answer: "red",
          promptTarget: "red",
          options: [
            { id: "blue", emoji: "🔑", label: "blue", color: "#5aa9e6" },
            { id: "red", emoji: "🔑", label: "red", color: "#ff6b6b" },
          ],
        },
        {
          type: "choice",
          instruction: "选择小狗",
          prompt: "Find the dog.",
          audio: "audio/boss-2-dog.mp3",
          answer: "dog",
          promptTarget: "dog",
          options: [
            { id: "cat", emoji: "🐱", label: "cat" },
            { id: "dog", emoji: "🐶", label: "dog" },
            { id: "bird", emoji: "🐦", label: "bird" },
          ],
        },
        {
          type: "word-forge",
          instruction: "按顺序拼出 CAT",
          prompt: "Build cat. C. A. T.",
          audio: "audio/boss-3-build-cat.mp3",
          answer: "CAT",
          letters: ["A", "T", "C"],
        },
        {
          type: "echo",
          instruction: "听示范并跟读",
          prompt: "Open the door.",
          audio: "audio/boss-4-open-door.mp3",
          accepted: ["open the door", "open door", "door"],
        },
      ],
      success: "The lighthouse is shining!",
      completion: "你用英语点亮了声音灯塔",
      completionTitle: "动物港得救了！",
      sceneReward: "✨ 动物港的声音灯塔完全修复",
    },
    {
      id: "level-9",
      number: 9,
      worldId: "school-city",
      title: "早安，老师",
      skill: "听问候认人物",
      type: "choice",
      instruction: "听到问候后，选择李老师",
      prompt: "Good morning, Ms. Lee.",
      promptTarget: "Ms. Lee",
      audio: "audio/school-good-morning.mp3",
      words: ["good morning", "teacher"],
      options: [
        { id: "doctor", emoji: "👩‍⚕️", label: "doctor" },
        { id: "teacher", emoji: "👩‍🏫", label: "Ms. Lee" },
        { id: "cook", emoji: "👨‍🍳", label: "cook" },
      ],
      answer: "teacher",
      success: "Good morning!",
      completion: "你会向老师说早安了",
      sceneReward: "🏫 小学城的校门打开了",
    },
    {
      id: "level-10",
      number: 10,
      worldId: "school-city",
      title: "向老师问好",
      skill: "开口说问候",
      type: "echo",
      instruction: "听示范，再向李老师问好",
      prompt: "Good morning, Ms. Lee.",
      audio: "audio/school-good-morning.mp3",
      words: ["good morning", "Ms. Lee"],
      accepted: ["good morning", "morning", "ms lee"],
      success: "Good morning!",
      completion: "你说出了 “Good morning”",
      sceneReward: "☀️ 教室的晨光亮起来了",
    },
    {
      id: "level-11",
      number: 11,
      worldId: "school-city",
      title: "进入教室",
      skill: "礼貌请求",
      type: "echo",
      instruction: "迟到或门关着时，可以这样询问",
      prompt: "May I come in?",
      audio: "audio/school-may-i-come-in.mp3",
      words: ["May I", "come in"],
      accepted: ["may i come in", "come in"],
      success: "Yes. Come in, please.",
      completion: "你学会了礼貌请求进入教室",
      sceneReward: "🚪 教室门为你打开了",
    },
    {
      id: "level-12",
      number: 12,
      worldId: "school-city",
      title: "我需要帮助",
      skill: "听句子选场景",
      type: "story",
      instruction: "选择正在向老师求助的画面",
      prompt: "I need help.",
      promptTarget: "help",
      audio: "audio/school-need-help.mp3",
      words: ["I need help"],
      options: [
        { id: "play", emoji: "🤹", label: "play" },
        { id: "help", emoji: "🙋‍♀️👩‍🏫", label: "ask for help" },
        { id: "sleep", emoji: "😴", label: "sleep" },
      ],
      answer: "help",
      success: "Yes. Ask for help.",
      completion: "遇到困难时，你会说 “I need help”",
      sceneReward: "🙋 求助小旗升起来了",
    },
    {
      id: "level-13",
      number: 13,
      worldId: "school-city",
      title: "这是我的书",
      skill: "听句子找物品",
      type: "choice",
      instruction: "选择句子里提到的学习用品",
      prompt: "This is my book.",
      promptTarget: "book",
      audio: "audio/school-my-book.mp3",
      words: ["book", "This is my"],
      options: [
        { id: "pencil", emoji: "✏️", label: "pencil" },
        { id: "book", emoji: "📘", label: "book" },
        { id: "bag", emoji: "🎒", label: "bag" },
      ],
      answer: "book",
      success: "Yes. Book.",
      completion: "你听懂了 “This is my book”",
      sceneReward: "📚 图书角整理好了",
    },
    {
      id: "level-14",
      number: 14,
      worldId: "school-city",
      title: "想去洗手间",
      skill: "校园礼貌表达",
      type: "echo",
      instruction: "需要离开教室时，先礼貌询问",
      prompt: "Can I go to the bathroom, please?",
      audio: "audio/school-bathroom.mp3",
      words: ["Can I", "bathroom", "please"],
      accepted: ["can i go", "bathroom", "please"],
      success: "Yes, you may.",
      completion: "你会礼貌询问去洗手间了",
      sceneReward: "🚻 校园路线牌点亮了",
    },
    {
      id: "level-15",
      number: 15,
      worldId: "school-city",
      title: "认识新朋友",
      skill: "主动邀请同伴",
      type: "echo",
      instruction: "听示范，再向新同学发出邀请",
      prompt: "Can we be friends?",
      audio: "audio/school-friends.mp3",
      words: ["friends", "Can we"],
      accepted: ["can we be friends", "be friends", "friends"],
      success: "Yes! Let's be friends.",
      completion: "你会主动认识新朋友了",
      sceneReward: "🤝 友谊长椅出现了",
    },
    {
      id: "level-16",
      number: 16,
      worldId: "school-city",
      title: "小学第一天 Boss",
      skill: "四段校园对话",
      type: "boss",
      instruction: "完成四项校园任务",
      prompt: "My first day at school!",
      words: ["book", "May I come in", "I need help", "thank you"],
      steps: [
        {
          type: "choice",
          instruction: "找到课本",
          prompt: "Find the book.",
          promptTarget: "book",
          audio: "audio/school-boss-find-book.mp3",
          answer: "book",
          options: [
            { id: "bag", emoji: "🎒", label: "bag" },
            { id: "book", emoji: "📘", label: "book" },
            { id: "pencil", emoji: "✏️", label: "pencil" },
          ],
        },
        {
          type: "echo",
          instruction: "礼貌进入教室",
          prompt: "May I come in?",
          audio: "audio/school-may-i-come-in.mp3",
          accepted: ["may i come in", "come in"],
        },
        {
          type: "choice",
          instruction: "选择求助场景",
          prompt: "I need help.",
          promptTarget: "help",
          audio: "audio/school-need-help.mp3",
          answer: "help",
          options: [
            { id: "run", emoji: "🏃", label: "run" },
            { id: "help", emoji: "🙋‍♂️👩‍🏫", label: "help" },
            { id: "eat", emoji: "🍎", label: "eat" },
          ],
        },
        {
          type: "echo",
          instruction: "向老师道谢",
          prompt: "Thank you, Ms. Lee.",
          audio: "audio/school-thank-you.mp3",
          accepted: ["thank you", "ms lee"],
        },
      ],
      success: "My first school day is complete!",
      completion: "你完成了小学第一天的校园对话",
      completionTitle: "小学第一天完成！",
      sceneReward: "🎒 小学城颁发了第一枚校徽",
    },
    {
      id: "level-17",
      number: 17,
      worldId: "life-town",
      title: "早餐想喝牛奶",
      skill: "表达自己的需要",
      type: "choice",
      instruction: "选择句子里想要的饮品",
      prompt: "I would like some milk, please.",
      promptTarget: "milk",
      audio: "audio/life-milk.mp3",
      words: ["I would like", "milk", "please"],
      options: [
        { id: "juice", emoji: "🧃", label: "juice" },
        { id: "milk", emoji: "🥛", label: "milk" },
        { id: "water", emoji: "💧", label: "water" },
      ],
      answer: "milk",
      success: "Here is your milk.",
      completion: "你会表达早餐想喝什么了",
      sceneReward: "🥛 早餐店开始营业了",
    },
    {
      id: "level-18",
      number: 18,
      worldId: "life-town",
      title: "穿鞋出门",
      skill: "听生活动作指令",
      type: "choice",
      instruction: "选择出门前要穿的物品",
      prompt: "Put on your shoes.",
      promptTarget: "shoes",
      audio: "audio/life-shoes.mp3",
      words: ["put on", "shoes"],
      options: [
        { id: "hat", emoji: "🧢", label: "hat" },
        { id: "shoes", emoji: "👟", label: "shoes" },
        { id: "gloves", emoji: "🧤", label: "gloves" },
      ],
      answer: "shoes",
      success: "Shoes on. Let's go!",
      completion: "你听懂了 “Put on your shoes”",
      sceneReward: "👟 上学小路出现了脚印",
    },
    {
      id: "level-19",
      number: 19,
      worldId: "life-town",
      title: "红灯要停",
      skill: "听安全指令",
      type: "story",
      instruction: "选择应该停下来的交通灯",
      prompt: "Stop at the red light.",
      promptTarget: "red",
      audio: "audio/life-red-light.mp3",
      words: ["stop", "red light"],
      options: [
        { id: "green", emoji: "🟢🚦", label: "green light" },
        { id: "red", emoji: "🔴🚦", label: "red light" },
        { id: "blue", emoji: "🔵🚦", label: "blue light" },
      ],
      answer: "red",
      success: "Stop and wait. Safe!",
      completion: "你听懂了红灯停车指令",
      sceneReward: "🚦 安全斑马线修好了",
    },
    {
      id: "level-20",
      number: 20,
      worldId: "life-town",
      title: "找不到铅笔",
      skill: "说明遇到的问题",
      type: "choice",
      instruction: "选择句子中找不到的物品",
      prompt: "I can't find my pencil.",
      promptTarget: "pencil",
      audio: "audio/life-pencil.mp3",
      words: ["I can't find", "pencil"],
      options: [
        { id: "ruler", emoji: "📏", label: "ruler" },
        { id: "pencil", emoji: "✏️", label: "pencil" },
        { id: "eraser", emoji: "🧽", label: "eraser" },
      ],
      answer: "pencil",
      success: "Here is your pencil.",
      completion: "你会说明自己找不到东西了",
      sceneReward: "✏️ 失物招领柜打开了",
    },
    {
      id: "level-21",
      number: 21,
      worldId: "life-town",
      title: "午餐想喝水",
      skill: "礼貌提出请求",
      type: "echo",
      instruction: "听示范，再礼貌请求一杯水",
      prompt: "Can I have some water, please?",
      audio: "audio/life-water.mp3",
      words: ["Can I have", "water", "please"],
      accepted: ["can i have", "some water", "water please"],
      success: "Of course. Here is some water.",
      completion: "你会礼貌请求一杯水了",
      sceneReward: "💧 饮水站开始工作了",
    },
    {
      id: "level-22",
      number: 22,
      worldId: "life-town",
      title: "我有点紧张",
      skill: "表达自己的感受",
      type: "story",
      instruction: "选择和 nervous 对应的表情",
      prompt: "I feel nervous.",
      promptTarget: "nervous",
      audio: "audio/life-nervous.mp3",
      words: ["I feel", "nervous"],
      options: [
        { id: "happy", emoji: "😄", label: "happy" },
        { id: "nervous", emoji: "😟", label: "nervous" },
        { id: "sleepy", emoji: "😴", label: "sleepy" },
      ],
      answer: "nervous",
      success: "It is okay to feel nervous.",
      completion: "你会表达“我有点紧张”了",
      sceneReward: "💛 心情小站亮起了暖灯",
    },
    {
      id: "level-23",
      number: 23,
      worldId: "life-town",
      title: "可以一起玩吗",
      skill: "加入同伴游戏",
      type: "echo",
      instruction: "听示范，再礼貌询问同伴",
      prompt: "Can I play with you?",
      audio: "audio/life-play-with-you.mp3",
      words: ["Can I", "play with you"],
      accepted: ["can i play", "play with you"],
      success: "Yes! Let's play together.",
      completion: "你会礼貌加入同伴游戏了",
      sceneReward: "🛝 生活小镇的操场开放了",
    },
    {
      id: "level-24",
      number: 24,
      worldId: "life-town",
      title: "上学日 Boss",
      skill: "四段生活对话",
      type: "boss",
      instruction: "完成从出门到放学的四项任务",
      prompt: "A day in Life Town!",
      words: ["shoes", "water", "happy", "see you tomorrow"],
      steps: [
        {
          type: "choice",
          instruction: "穿鞋准备出门",
          prompt: "Put on your shoes.",
          promptTarget: "shoes",
          audio: "audio/life-shoes.mp3",
          answer: "shoes",
          options: [
            { id: "shoes", emoji: "👟", label: "shoes" },
            { id: "book", emoji: "📘", label: "book" },
            { id: "cup", emoji: "🥤", label: "cup" },
          ],
        },
        {
          type: "echo",
          instruction: "午餐时请求喝水",
          prompt: "Can I have some water, please?",
          audio: "audio/life-water.mp3",
          accepted: ["can i have", "some water", "water please"],
        },
        {
          type: "choice",
          instruction: "选择开心的表情",
          prompt: "I feel happy.",
          promptTarget: "happy",
          audio: "audio/life-happy.mp3",
          answer: "happy",
          options: [
            { id: "sad", emoji: "😢", label: "sad" },
            { id: "happy", emoji: "😄", label: "happy" },
            { id: "tired", emoji: "🥱", label: "tired" },
          ],
        },
        {
          type: "echo",
          instruction: "放学时和朋友道别",
          prompt: "See you tomorrow!",
          audio: "audio/life-see-you.mp3",
          accepted: ["see you", "tomorrow"],
        },
      ],
      success: "My school day is complete!",
      completion: "你完成了一个上学日的生活英语",
      completionTitle: "生活小镇任务完成！",
      sceneReward: "🌇 放学钟声响起来了",
    },
    {
      id: "level-25",
      number: 25,
      worldId: "idiom-island",
      title: "一心一意",
      skill: "看画面理解成语",
      type: "story",
      instruction: "哪个孩子在专心做同一件事",
      prompt: "一心一意。",
      promptTarget: "一心一意",
      audio: "audio/idiom-focus.mp3",
      words: ["一心一意"],
      options: [
        { id: "distracted", emoji: "📺🎮📖😵", label: "同时做很多事" },
        { id: "focus", emoji: "🧒📖✨", label: "专心读一本书" },
        { id: "sleep", emoji: "🛌💤", label: "正在睡觉" },
      ],
      answer: "focus",
      success: "一心一意，就是专心做好一件事。",
      completion: "你理解了“一心一意”",
      sceneReward: "🎯 专注星点亮了",
    },
    {
      id: "level-26",
      number: 26,
      worldId: "idiom-island",
      title: "井井有条",
      skill: "看画面理解成语",
      type: "story",
      instruction: "哪个书桌摆放得整齐、有顺序",
      prompt: "井井有条。",
      promptTarget: "井井有条",
      audio: "audio/idiom-order.mp3",
      words: ["井井有条"],
      options: [
        { id: "messy", emoji: "📚🧦🖍️💥", label: "乱成一团" },
        { id: "empty", emoji: "🪹", label: "什么也没有" },
        { id: "order", emoji: "📚📒✏️✅", label: "分类摆整齐" },
      ],
      answer: "order",
      success: "井井有条，就是整齐而有顺序。",
      completion: "你理解了“井井有条”",
      sceneReward: "🗂️ 成语岛的书架整理好了",
    },
    {
      id: "level-27",
      number: 27,
      worldId: "idiom-island",
      title: "助人为乐",
      skill: "看故事理解成语",
      type: "story",
      instruction: "哪个孩子主动帮助了别人",
      prompt: "助人为乐。",
      promptTarget: "助人为乐",
      audio: "audio/idiom-help.mp3",
      words: ["助人为乐"],
      options: [
        { id: "ignore", emoji: "🙈", label: "假装没看见" },
        { id: "help", emoji: "🧒🤝👧", label: "扶起摔倒的同学" },
        { id: "take", emoji: "🧒🍪🍪", label: "拿走两块饼干" },
      ],
      answer: "help",
      success: "助人为乐，就是帮助别人并感到快乐。",
      completion: "你理解了“助人为乐”",
      sceneReward: "🤝 互助桥连接了两座小岛",
    },
    {
      id: "level-28",
      number: 28,
      worldId: "idiom-island",
      title: "画龙点睛",
      skill: "看故事理解成语",
      type: "story",
      instruction: "哪一步让整幅画一下子有了精神",
      prompt: "画龙点睛。",
      promptTarget: "画龙点睛",
      audio: "audio/idiom-dragon.mp3",
      words: ["画龙点睛"],
      options: [
        { id: "paper", emoji: "📄", label: "拿出一张白纸" },
        { id: "color", emoji: "🎨", label: "准备许多颜料" },
        { id: "eyes", emoji: "🐉👀✨", label: "给龙画上眼睛" },
      ],
      answer: "eyes",
      success: "画龙点睛，就是加上最重要的一笔。",
      completion: "你理解了“画龙点睛”",
      completionTitle: "四座学习岛全部点亮！",
      sceneReward: "🐉 成语龙睁开了眼睛",
    },
  ];
})(typeof globalThis !== "undefined" ? globalThis : this);
